package names

import (
	"fmt"

	"github.com/Galdoba/cepheus/pkg/dice"
)

var Lists = [][]string{
	[]string{"Kaelian", "Zorya", "Valerium"},
	[]string{"Darian", "Elara", "Navarr"},
	[]string{"Torin", "Lyra", "Corvus"},
	[]string{"Zevran", "Seren", "Orionis"},
	[]string{"Kaelen", "Nyx", "Solarix"},
	[]string{"Cassian", "Elysia", "Cade"},
	[]string{"Jaxar", "Isolde", "Starkos"},
	[]string{"Lorian", "Thalia", "Vega"},
	[]string{"Orion", "Aurora", "Caelum"},
	[]string{"Zander", "Cyra", "Zenith"},
	[]string{"Rhydian", "Maia", "Novak"},
	[]string{"Soren", "Lumina", "Cross"},
	[]string{"Kaelum", "Theia", "Rook"},
	[]string{"Jovan", "Elara", "Stellan"},
	[]string{"Daxos", "Nerys", "Blackwood"},
	[]string{"Torven", "Anya", "Kael"},
	[]string{"Lysander", "Valeria", "Riven"},
	[]string{"Zarek", "Helene", "Crest"},
	[]string{"Cyprian", "Selene", "Arden"},
	[]string{"Kaelor", "Ione", "Draken"},
	[]string{"Phelan", "Calista", "Rhys"},
	[]string{"Tavian", "Elara", "Jet"},
	[]string{"Orin", "Seraphina", "Wilde"},
	[]string{"Zenon", "Cygnus", "Reed"},
	[]string{"Kaelis", "Lyric", "Storm"},
	[]string{"Darien", "Cassiopeia", "Hawke"},
	[]string{"Jarek", "Andromeda", "Vance"},
	[]string{"Lucien", "Eos", "Sable"},
	[]string{"Zephyr", "Belinda", "Slade"},
	[]string{"Kaelan", "Nova", "Blaze"},
	[]string{"Rhys", "Elara", "Knight"},
	[]string{"Sylas", "Ophelia", "Frost"},
	[]string{"Toril", "Persephone", "Shade"},
	[]string{"Varian", "Artemis", "Stone"},
	[]string{"Xander", "Calliope", "Thorne"},
	[]string{"Yorin", "Lilith", "Ash"},
	[]string{"Zale", "Morrigan", "Ember"},
	[]string{"Kaelius", "Eirian", "Phoenix"},
	[]string{"Dax", "Lunara", "Raven"},
	[]string{"Jorin", "Melusine", "Shadow"},
	[]string{"Lykos", "Sirius", "Cinder"},
	[]string{"Nyx", "Terra", "Gale"},
	[]string{"Osian", "Vega", "Cliff"},
	[]string{"Pryderi", "Rhea", "Ridge"},
	[]string{"Quillon", "Solana", "Peak"},
	[]string{"Rurik", "Umbra", "Vale"},
	[]string{"Saelen", "Willow", "Brook"},
	[]string{"Talon", "Yvaine", "Locke"},
	[]string{"Ulric", "Zinnia", "Ford"},
	[]string{"Kaelos", "Astra", "Ridge"},
	[]string{"Dagan", "Briar", "Wood"},
	[]string{"Jett", "Clover", "Field"},
	[]string{"Korbin", "Dahlia", "Glen"},
	[]string{"Linden", "Flora", "Marsh"},
	[]string{"Maddox", "Gaia", "Heath"},
	[]string{"Nash", "Hazel", "Moss"},
	[]string{"Oberon", "Iris", "Pond"},
	[]string{"Pax", "Jasmine", "Stream"},
	[]string{"Quade", "Kestra", "Swamp"},
	[]string{"Ridge", "Laurel", "Tarn"},
	[]string{"Shea", "Magnolia", "Fen"},
	[]string{"Trent", "Olive", "Bog"},
	[]string{"Vance", "Petra", "Fjord"},
	[]string{"Wells", "Rose", "Lake"},
	[]string{"Xeno", "Sage", "Mere"},
	[]string{"York", "Tansy", "Pool"},
	[]string{"Zeke", "Veronica", "Isle"},
	[]string{"Kaelen", "Wisteria", "Shore"},
	[]string{"Arvid", "Acacia", "Bay"},
	[]string{"Bastian", "Amber", "Cape"},
	[]string{"Cedric", "Azalea", "Point"},
	[]string{"Dmitri", "Blossom", "Spit"},
	[]string{"Eldon", "Camellia", "Key"},
	[]string{"Fintan", "Chrys", "Dune"},
	[]string{"Gareth", "Daphne", "Oasis"},
	[]string{"Harlan", "Ember", "Atoll"},
	[]string{"Ivan", "Faye", "Reef"},
	[]string{"Jules", "Ginger", "Cay"},
	[]string{"Kael", "Glynn", "Islet"},
	[]string{"Leif", "Holly", "Shoal"},
	[]string{"Milo", "Indigo", "Skerry"},
	[]string{"Nils", "Jewel", "Bar"},
	[]string{"Odin", "Kalina", "Spur"},
	[]string{"Peri", "Lark", "Pass"},
	[]string{"Quill", "Marigold", "Gap"},
	[]string{"Rune", "Meadow", "Col"},
	[]string{"Stig", "Nectar", "Notch"},
	[]string{"Sven", "Orchid", "Defile"},
	[]string{"Tygo", "Peony", "Gorge"},
	[]string{"Ulf", "Quinn", "Gully"},
	[]string{"Viggo", "Rain", "Ravine"},
	[]string{"Walt", "Saffron", "Chasm"},
	[]string{"Xerxes", "Sunny", "Crevasse"},
	[]string{"Yale", "Tansy", "Abyss"},
	[]string{"Zane", "Violet", "Deep"},
	[]string{"Kael", "Tansy", "Rift"},
	[]string{"Bram", "Alba", "Summit"},
	[]string{"Cai", "Beta", "Ridge"},
	[]string{"Draco", "Calypso", "Pinnacle"},
	[]string{"Eros", "Delta", "Crest"},
	[]string{"Faron", "Echo", "Spire"},
	[]string{"Gideon", "Gemini", "Apex"},
	[]string{"Hector", "Hera", "Crown"},
	[]string{"Icarus", "Io", "Cap"},
	[]string{"Juno", "Jupiter", "Head"},
	[]string{"Kratos", "Luna", "Tor"},
	[]string{"Leo", "Lyra", "Ben"},
	[]string{"Mars", "Maia", "Dun"},
	[]string{"Nemo", "Mars", "Mount"},
	[]string{"Odin", "Mira", "Peak"},
	[]string{"Pluto", "Nix", "Top"},
	[]string{"Quasar", "Oberon", "Brow"},
	[]string{"Rigel", "Pandora", "Nose"},
	[]string{"Sol", "Rhea", "Shoulder"},
	[]string{"Titan", "Selene", "Knoll"},
	[]string{"Ulysses", "Tethys", "Hill"},
	[]string{"Vulcan", "Thebe", "Down"},
	[]string{"Wolf", "Venus", "Fell"},
	[]string{"Xerxes", "Vesta", "Law"},
	[]string{"Ymir", "Yara", "Edge"},
	[]string{"Zagan", "Ziva", "Bank"},
	[]string{"Kael", "Zora", "Slope"},
	[]string{"Aeson", "Aelia", "Decline"},
	[]string{"Beron", "Ania", "Incline"},
	[]string{"Ceron", "Basia", "Grade"},
	[]string{"Deron", "Celia", "Ramp"},
	[]string{"Eron", "Dacia", "Tilt"},
	[]string{"Ferox", "Eira", "List"},
	[]string{"Gerox", "Fabia", "Cant"},
	[]string{"Heron", "Galia", "Lean"},
	[]string{"Irox", "Helvia", "Pitch"},
	[]string{"Jeron", "Ilia", "Angle"},
	[]string{"Keron", "Justa", "Bevel"},
	[]string{"Leron", "Livia", "Slant"},
	[]string{"Meron", "Maia", "Camber"},
	[]string{"Neron", "Nerva", "Curve"},
	[]string{"Oeron", "Octa", "Bend"},
	[]string{"Peron", "Paula", "Arc"},
	[]string{"Qeron", "Quinta", "Arch"},
	[]string{"Reron", "Rufina", "Bow"},
	[]string{"Seron", "Secunda", "Coil"},
	[]string{"Terox", "Tertia", "Twist"},
	[]string{"Uron", "Urbana", "Loop"},
	[]string{"Varon", "Valeria", "Spiral"},
	[]string{"Weron", "Vibia", "Helix"},
	[]string{"Xeron", "Xenia", "Whorl"},
	[]string{"Yeron", "Yuva", "Curlicue"},
	[]string{"Zeron", "Zosia", "Volute"},
	[]string{"Kael", "Zanna", "Scroll"},
	[]string{"Aion", "Alta", "Wave"},
	[]string{"Bion", "Beta", "Surge"},
	[]string{"Cion", "Cyma", "Swirl"},
	[]string{"Dion", "Delta", "Eddy"},
	[]string{"Eion", "Eira", "Drift"},
	[]string{"Fion", "Flux", "Flow"},
	[]string{"Gion", "Gamma", "Flux"},
	[]string{"Hion", "Helia", "Tide"},
	[]string{"Iion", "Iota", "Current"},
	[]string{"Jion", "Jora", "Stream"},
	[]string{"Kion", "Kappa", "Runnel"},
	[]string{"Lion", "Lambda", "Rill"},
	[]string{"Mion", "Mu", "Rivulet"},
	[]string{"Nion", "Nu", "Runnel"},
	[]string{"Oion", "Omicron", "Rill"},
	[]string{"Pion", "Pi", "Race"},
	[]string{"Qion", "Qora", "Spate"},
	[]string{"Rion", "Rho", "Spurt"},
	[]string{"Sion", "Sigma", "Gush"},
	[]string{"Tion", "Tau", "Spout"},
	[]string{"Uion", "Upsilon", "Geyser"},
	[]string{"Vion", "Phi", "Well"},
	[]string{"Wion", "Chi", "Fount"},
	[]string{"Xion", "Psi", "Spring"},
	[]string{"Yion", "Omega", "Source"},
	[]string{"Zion", "Alpha", "Origin"},
	[]string{"Kael", "Astra", "Genesis"},
	[]string{"Corbin", "Lyra", "Vesper"},
	[]string{"Draxon", "Nova", "Orion"},
	[]string{"Ezran", "Solara", "Cyrus"},
	[]string{"Fynne", "Cyane", "Zenon"},
	[]string{"Gryff", "Lunara", "Helios"},
	[]string{"Jett", "Zorya", "Atlas"},
	[]string{"Kael", "Rhea", "Perseus"},
	[]string{"Lyr", "Celeste", "Arturus"},
	[]string{"Mace", "Andra", "Draco"},
	[]string{"Nyx", "Elara", "Cassiopeia"},
	[]string{"Orin", "Seren", "Lyra"},
	[]string{"Pax", "Thalia", "Orionis"},
	[]string{"Quinn", "Eos", "Solarix"},
	[]string{"Rook", "Aurora", "Zenith"},
	[]string{"Sage", "Maia", "Novak"},
	[]string{"Talon", "Nyx", "Cross"},
	[]string{"Vale", "Theia", "Rook"},
	[]string{"Wren", "Selene", "Stellan"},
	[]string{"Xander", "Lumina", "Blackwood"},
	[]string{"York", "Ione", "Kael"},
	[]string{"Zane", "Calista", "Riven"},
	[]string{"Kael", "Anya", "Crest"},
	[]string{"Bane", "Belinda", "Arden"},
	[]string{"Cade", "Cassiopeia", "Draken"},
	[]string{"Dane", "Elara", "Rhys"},
	[]string{"Egan", "Helene", "Jet"},
	[]string{"Finn", "Isolde", "Wilde"},
	[]string{"Gage", "Melusine", "Reed"},
	[]string{"Hale", "Ophelia", "Storm"},
	[]string{"Ivan", "Persephone", "Hawke"},
	[]string{"Jace", "Artemis", "Vance"},
	[]string{"Kobe", "Calliope", "Sable"},
	[]string{"Lane", "Morrigan", "Slade"},
	[]string{"Mace", "Nova", "Blaze"},
	[]string{"Nate", "Willow", "Knight"},
	[]string{"Owen", "Yvaine", "Frost"},
	[]string{"Pierce", "Zinnia", "Shade"},
	[]string{"Quade", "Astra", "Stone"},
	[]string{"Reed", "Briar", "Thorne"},
	[]string{"Shade", "Clover", "Ash"},
	[]string{"Troy", "Dahlia", "Ember"},
	[]string{"Vance", "Flora", "Phoenix"},
	[]string{"Wade", "Gaia", "Raven"},
	[]string{"Xavier", "Hazel", "Shadow"},
	[]string{"Yale", "Iris", "Cinder"},
	[]string{"Zeke", "Jasmine", "Gale"},
	[]string{"Kael", "Laurel", "Cliff"},
	[]string{"Arlo", "Magnolia", "Ridge"},
	[]string{"Brio", "Olive", "Peak"},
	[]string{"Cairo", "Petra", "Vale"},
	[]string{"Dario", "Rose", "Locke"},
	[]string{"Elio", "Sage", "Ford"},
	[]string{"Fabian", "Tansy", "Ridge"},
	[]string{"Gian", "Veronica", "Wood"},
	[]string{"Hugo", "Wisteria", "Field"},
	[]string{"Ivo", "Acacia", "Glen"},
	[]string{"Jairo", "Amber", "Marsh"},
	[]string{"Kaito", "Azalea", "Heath"},
	[]string{"Leo", "Blossom", "Moss"},
	[]string{"Marco", "Camellia", "Pond"},
	[]string{"Nico", "Chrys", "Stream"},
	[]string{"Orio", "Daphne", "Swamp"},
	[]string{"Pablo", "Ember", "Tarn"},
	[]string{"Rio", "Faye", "Fen"},
	[]string{"Silas", "Ginger", "Bog"},
	[]string{"Theo", "Holly", "Fjord"},
	[]string{"Vigo", "Indigo", "Lake"},
	[]string{"Wesley", "Jewel", "Mere"},
	[]string{"Xavi", "Kalina", "Pool"},
	[]string{"Yves", "Lark", "Isle"},
	[]string{"Zion", "Marigold", "Shore"},
	[]string{"Kael", "Meadow", "Bay"},
	[]string{"Ash", "Nectar", "Cape"},
	[]string{"Blaze", "Orchid", "Point"},
	[]string{"Clay", "Peony", "Spit"},
	[]string{"Dust", "Quinn", "Key"},
	[]string{"Echo", "Rain", "Dune"},
	[]string{"Flame", "Saffron", "Oasis"},
	[]string{"Gale", "Sunny", "Atoll"},
	[]string{"Haze", "Tansy", "Reef"},
	[]string{"Ice", "Violet", "Cay"},
	[]string{"Jet", "Alba", "Islet"},
	[]string{"Knight", "Beta", "Shoal"},
	[]string{"Lake", "Calypso", "Skerry"},
	[]string{"Mist", "Delta", "Bar"},
	[]string{"North", "Echo", "Spur"},
	[]string{"Petal", "Gemini", "Pass"},
	[]string{"Quartz", "Hera", "Gap"},
	[]string{"Rust", "Io", "Col"},
	[]string{"Sky", "Jupiter", "Notch"},
	[]string{"Stone", "Luna", "Defile"},
	[]string{"Thorn", "Mars", "Gorge"},
	[]string{"Umbra", "Mira", "Gully"},
	[]string{"Vapor", "Nix", "Ravine"},
	[]string{"Wave", "Oberon", "Chasm"},
	[]string{"Yarn", "Pandora", "Crevasse"},
	[]string{"Zenith", "Rhea", "Abyss"},
	[]string{"Kael", "Selene", "Deep"},
	[]string{"Apex", "Tethys", "Rift"},
	[]string{"Bluff", "Thebe", "Summit"},
	[]string{"Cliff", "Venus", "Ridge"},
	[]string{"Crag", "Vesta", "Pinnacle"},
	[]string{"Drift", "Yara", "Crest"},
	[]string{"Edge", "Ziva", "Spire"},
	[]string{"Fjord", "Zora", "Apex"},
	[]string{"Gorge", "Aelia", "Crown"},
	[]string{"Hill", "Ania", "Cap"},
	[]string{"Knoll", "Basia", "Head"},
	[]string{"Ledge", "Celia", "Tor"},
	[]string{"Mesa", "Dacia", "Ben"},
	[]string{"Peak", "Eira", "Dun"},
	[]string{"Ridge", "Fabia", "Mount"},
	[]string{"Spire", "Galia", "Peak"},
	[]string{"Summit", "Helvia", "Top"},
	[]string{"Tor", "Ilia", "Brow"},
	[]string{"Butte", "Justa", "Nose"},
	[]string{"Dune", "Livia", "Shoulder"},
	[]string{"Vale", "Maia", "Knoll"},
	[]string{"Wold", "Nerva", "Hill"},
	[]string{"Bluff", "Octa", "Down"},
	[]string{"Brow", "Paula", "Fell"},
	[]string{"Crest", "Quinta", "Law"},
	[]string{"Nose", "Rufina", "Edge"},
	[]string{"Spur", "Secunda", "Bank"},
	[]string{"Berm", "Tertia", "Slope"},
	[]string{"Bank", "Urbana", "Decline"},
	[]string{"Barrow", "Valeria", "Incline"},
	[]string{"Cairn", "Vibia", "Grade"},
	[]string{"Delta", "Xenia", "Ramp"},
	[]string{"Dome", "Yuva", "Tilt"},
	[]string{"Esker", "Zosia", "List"},
	[]string{"Finger", "Zanna", "Cant"},
	[]string{"Hogback", "Alta", "Lean"},
	[]string{"Hummock", "Beta", "Pitch"},
	[]string{"Kame", "Cyma", "Angle"},
	[]string{"Knob", "Delta", "Bevel"},
	[]string{"Monadnock", "Eira", "Slant"},
	[]string{"Motte", "Flux", "Camber"},
	[]string{"Outcrop", "Gamma", "Curve"},
	[]string{"Pingo", "Helia", "Bend"},
	[]string{"Pyramid", "Iota", "Arc"},
	[]string{"Shoal", "Jora", "Arch"},
	[]string{"Teardrop", "Kappa", "Bow"},
	[]string{"Uvala", "Lambda", "Coil"},
	[]string{"Ventifact", "Mu", "Twist"},
	[]string{"Waterfall", "Nu", "Loop"},
	[]string{"Yazoo", "Omicron", "Spiral"},
	[]string{"Zibar", "Pi", "Helix"},
	[]string{"Kael", "Qora", "Whorl"},
	[]string{"Arch", "Rho", "Curlicue"},
	[]string{"Bend", "Sigma", "Volute"},
	[]string{"Coil", "Tau", "Scroll"},
	[]string{"Curve", "Upsilon", "Wave"},
	[]string{"Fold", "Phi", "Surge"},
	[]string{"Hairpin", "Chi", "Swirl"},
	[]string{"Helix", "Psi", "Eddy"},
	[]string{"Loop", "Omega", "Drift"},
	[]string{"Meander", "Alpha", "Flow"},
	[]string{"Oxbow", "Astra", "Flux"},
	[]string{"Switchback", "Lyra", "Tide"},
	[]string{"Traverse", "Nova", "Current"},
	[]string{"Twist", "Orion", "Stream"},
	[]string{"Whorl", "Solara", "Runnel"},
	[]string{"Zigzag", "Cyane", "Rill"},
	[]string{"Kael", "Lunara", "Rivulet"},
	[]string{"Male_Name", "Female_Name", "Surname"},
	[]string{"Kaelian", "Zr'ella", "Ktharr"},
	[]string{"Darian", "Grisha", "Vogorn"},
	[]string{"Torin", "Xylia", "Qitari"},
	[]string{"Thragg", "Thressa", "Gornn"},
	[]string{"Kztak", "K'vira", "Tchakk"},
	[]string{"Vorlag", "Vexxa", "Laggs"},
	[]string{"Ploov", "Pliis", "Vort"},
	[]string{"Quorrin", "Quessa", "Rinn"},
	[]string{"Jylys", "Jyra", "Lyss"},
	[]string{"Floxx", "Fleena", "Xxorr"},
	[]string{"Zxulan", "Z'neera", "Linthaar"},
	[]string{"Gorthun", "Grelda", "Unbrak"},
	[]string{"Xanthur", "Xiara", "Urzhad"},
	[]string{"Trog", "Trilla", "Gnak"},
	[]string{"Klatho", "K'ressa", "Hoban"},
	[]string{"Vortan", "Vyssa", "Antross"},
	[]string{"Pkarr", "P'lina", "Arrgoth"},
	[]string{"Quorgil", "Quara", "Gilmar"},
	[]string{"Jhastar", "Jhessa", "Starnel"},
	[]string{"Fnoor", "F'lissa", "Oortek"},
	[]string{"Zulgarn", "Zara", "Garnzek"},
	[]string{"Grikk", "Grelia", "Kkvol"},
	[]string{"Xevar", "Xena", "Varquisthul"},
	[]string{"Ban", "Thia", "Bandor"},
	[]string{"Krazak", "Krina", "Zaktar"},
	[]string{"Vossk", "Vera", "Sskhal"},
	[]string{"Pryxx", "Priya", "Xxorn"},
	[]string{"Qzan", "Q'ora", "Anzoth"},
	[]string{"Jaxom", "Jara", "Ombrey"},
	[]string{"Fyrdek", "Fyra", "Deklon"},
	[]string{"Zborak", "Z'lena", "Rakshi"},
	[]string{"Grendar", "Grexa", "Argul"},
	[]string{"Xithos", "Xira", "Oskarn"},
	[]string{"Trokk", "Talia", "Kkmor"},
	[]string{"Kvorn", "K'lena", "Ornsk"},
	[]string{"Volnix", "Volta", "Ixpria"},
	[]string{"Ptalon", "P'thea", "Lonzar"},
	[]string{"Quibos", "Quila", "Osqen"},
	[]string{"Jovos", "Jora", "Osvell"},
	[]string{"Flint", "F'lya", "Intvor"},
	[]string{"Zalanth", "Zara", "Anthzor"},
	[]string{"Ghanal", "Gha'ra", "Nalsen"},
	[]string{"Xortic", "Xor'na", "Ticvell"},
	[]string{"Thraxx", "Thora", "Xxarn"},
	[]string{"Kozar", "Kora", "Zarnik"},
	[]string{"Vkoss", "V'nessa", "Osskarr"},
	[]string{"Phendor", "Phena", "Ordis"},
	[]string{"Qarth", "Q'ira", "Arthvol"},
	[]string{"Jhalen", "Jhaya", "Enkar"},
	[]string{"Fyrgon", "Fyrra", "Gontek"},
	[]string{"Zvokk", "Z'vira", "Okarr"},
	[]string{"Gralnex", "Gralia", "Extern"},
	[]string{"Xandor", "Xan'tha", "Orqex"},
	[]string{"Thulkor", "Thul'ra", "Kormax"},
	[]string{"Kzann", "K'zara", "Annbor"},
	[]string{"Vorqex", "Vor'na", "Exzul"},
	[]string{"Plonar", "Plo'via", "Narthel"},
	[]string{"Quordis", "Quor'la", "Isqarn"},
	[]string{"Jyvoss", "Jy'nessa", "Osskell"},
	[]string{"Floxnar", "Flox'ira", "Narzin"},
	[]string{"Zorqeth", "Zor'lena", "Qethvol"},
	[]string{"Graxill", "Grax'na", "Illvor"},
	[]string{"Xyloth", "Xyl'ara", "Othzann"},
	[]string{"Thrakonn", "Thrak'ea", "Onngarr"},
	[]string{"Kvell", "K'voss", "Ellzarr"},
	[]string{"Vognn", "Vog'ira", "Nnkort"},
	[]string{"Ptarr", "P'tess", "Arrzikk"},
	[]string{"Quiblor", "Quib'ra", "Lorqex"},
	[]string{"Jaxonn", "Jax'ira", "Onnvell"},
	[]string{"Fynnar", "Fyn'essa", "Arzokk"},
	[]string{"Zulqar", "Zul'tha", "Qarzann"},
	[]string{"Griklor", "Grik'na", "Lorthex"},
	[]string{"Xevoss", "Xe'vira", "Ossqarn"},
	[]string{"Thulmarr", "Thul'mia", "Arrzoth"},
	[]string{"Krazikk", "Kraz'na", "Ikkvor"},
	[]string{"Voskar", "Vos'la", "Karnell"},
	[]string{"Pryqex", "Pry'nia", "Extall"},
	[]string{"Qvarr", "Q'voss", "Arrzul"},
	[]string{"Jhorak", "Jho'ra", "Raknell"},
	[]string{"Fyrzann", "Fyr'zira", "Annkoss"},
	[]string{"Zborr", "Z'nessa", "Orrqex"},
	[]string{"Grentek", "Gren'ta", "Ekvor"},
	[]string{"Xitharr", "Xit'hera", "Arrzikk"},
	[]string{"Trokonn", "Trok'na", "Onngess"},
	[]string{"Kvorr", "K'viss", "Orrtall"},
	[]string{"Volqex", "Vol'nia", "Exzarr"},
	[]string{"Ptorr", "P'tara", "Orrkess"},
	[]string{"Quivoss", "Qui'vira", "Osszann"},
	[]string{"Jovkarr", "Jov'kess", "Arrnell"},
	[]string{"Flarr", "F'liss", "Arrzex"},
	[]string{"Zalqor", "Zal'qia", "Orzenn"},
	[]string{"Ghavoss", "Gha'vira", "Ossbor"},
	[]string{"Xortall", "Xor'tess", "Allzarr"},
	[]string{"Thraqex", "Thra'qia", "Exvorn"},
	[]string{"Kozvarr", "Koz'vess", "Arrnell"},
	[]string{"Vkarr", "V'kess", "Arrzull"},
	[]string{"Phenqor", "Phen'qia", "Orzakk"},
	[]string{"Qzann", "Q'zira", "Annvoss"},
	[]string{"Jhalkarr", "Jhal'kess", "Arrthenn"},
	[]string{"Fyrvoss", "Fyr'vira", "Ossqor"},
	[]string{"Zvarr", "Z'vess", "Arrzinn"},
	[]string{"Gralqex", "Gral'qia", "Extorr"},
	[]string{"Xanvoss", "Xan'vira", "Ossborr"},
	[]string{"Thulqor", "Thul'qia", "Orzenn"},
	[]string{"Kzarr", "K'zess", "Arrvokk"},
	[]string{"Vortall", "Vor'tess", "Allzorr"},
	[]string{"Ploqex", "Plo'qia", "Exvarr"},
	[]string{"Quorvoss", "Quor'vira", "Osszenn"},
	[]string{"Jyzarr", "Jy'zess", "Arrlorr"},
	[]string{"Floxqor", "Flox'qia", "Orvinn"},
	[]string{"Zortall", "Zor'tess", "Allqenn"},
	[]string{"Graxqex", "Grax'qia", "Exlorr"},
	[]string{"Xylvoss", "Xyl'vira", "Osstenn"},
	[]string{"Thrakzarr", "Thrak'zess", "Arrqorr"},
	[]string{"Kvarr", "K'vess", "Arrtenn"},
	[]string{"Vogqor", "Vog'qia", "Orzinn"},
	[]string{"Ptall", "P'tess", "Allvarr"},
	[]string{"Quibvoss", "Quib'vira", "Ossqinn"},
	[]string{"Jaxzarr", "Jax'zess", "Arrborr"},
	[]string{"Fynqor", "Fyn'qia", "Ortenn"},
	[]string{"Zulvoss", "Zul'vira", "Ossqarr"},
	[]string{"Grikzarr", "Grik'zess", "Arrlenn"},
	[]string{"Xeqor", "Xe'qia", "Orvarr"},
	[]string{"Thulvoss", "Thul'vira", "Osslenn"},
	[]string{"Krazzarr", "Kraz'zess", "Arrqarr"},
	[]string{"Vosqor", "Vos'qia", "Ortarr"},
	[]string{"Pryvoss", "Pry'vira", "Osslarr"},
	[]string{"Qzorr", "Q'zira", "Orrtenn"},
	[]string{"Jhovoss", "Jho'vira", "Ossqorr"},
	[]string{"Fyrzorr", "Fyr'zira", "Orrlarr"},
	[]string{"Zborr", "Z'vira", "Orrqarr"},
	[]string{"Grenvoss", "Gren'vira", "Osstorr"},
	[]string{"Xitzorr", "Xit'zira", "Orrlarr"},
	[]string{"Trokvoss", "Trok'vira", "Ossqorr"},
	[]string{"Kzorr", "K'zira", "Orrtarr"},
	[]string{"Volvoss", "Vol'vira", "Osslarr"},
	[]string{"Pzorr", "P'zira", "Orrqarr"},
	[]string{"Quivoss", "Qui'vira", "Osstarr"},
	[]string{"Jovzorr", "Jov'zira", "Orrlarr"},
	[]string{"Fvoss", "F'vira", "Ossqarr"},
	[]string{"Zalzorr", "Zal'zira", "Orrtarr"},
	[]string{"Ghavoss", "Gha'vira", "Osslarr"},
	[]string{"Xorzorr", "Xor'zira", "Orrqarr"},
	[]string{"Thravoss", "Thra'vira", "Osstarr"},
	[]string{"Kozzorr", "Koz'zira", "Orrlarr"},
	[]string{"Vzorr", "V'zira", "Ossqarr"},
	[]string{"Phenvoss", "Phen'vira", "Osstarr"},
	[]string{"Qzorr", "Q'zira", "Orrlarr"},
	[]string{"Jhalvoss", "Jhal'vira", "Ossqarr"},
	[]string{"Fyrzorr", "Fyr'zira", "Osstarr"},
	[]string{"Zzorr", "Z'zira", "Orrlarr"},
	[]string{"Gralvoss", "Gral'vira", "Ossqarr"},
	[]string{"Xanzorr", "Xan'zira", "Osstarr"},
	[]string{"Thulvoss", "Thul'vira", "Orrlarr"},
	[]string{"Kvoss", "K'vira", "Ossqarr"},
	[]string{"Vorzorr", "Vor'zira", "Osstarr"},
	[]string{"Plovoss", "Plo'vira", "Orrlarr"},
	[]string{"Quorzorr", "Quor'zira", "Ossqarr"},
	[]string{"Jyvoss", "Jy'vira", "Osstarr"},
	[]string{"Floxzorr", "Flox'zira", "Orrlarr"},
	[]string{"Zorvoss", "Zor'vira", "Ossqarr"},
	[]string{"Graxzorr", "Grax'zira", "Osstarr"},
	[]string{"Xylvoss", "Xyl'vira", "Orrlarr"},
	[]string{"Thrakzorr", "Thrak'zira", "Ossqarr"},
	[]string{"Kzorr", "K'zira", "Osstarr"},
	[]string{"Vogvoss", "Vog'vira", "Orrlarr"},
	[]string{"Pzorr", "P'zira", "Ossqarr"},
	[]string{"Quibvoss", "Quib'vira", "Osstarr"},
	[]string{"Jaxzorr", "Jax'zira", "Orrlarr"},
	[]string{"Fynvoss", "Fyn'vira", "Ossqarr"},
	[]string{"Zulzorr", "Zul'zira", "Osstarr"},
	[]string{"Grikvoss", "Grik'vira", "Orrlarr"},
	[]string{"Xezorr", "Xe'zira", "Ossqarr"},
	[]string{"Thulzorr", "Thul'zira", "Osstarr"},
	[]string{"Krazvoss", "Kraz'vira", "Orrlarr"},
	[]string{"Voszorr", "Vos'zira", "Ossqarr"},
	[]string{"Pryvoss", "Pry'vira", "Osstarr"},
	[]string{"Qzorr", "Q'zira", "Orrlarr"},
	[]string{"Jhovoss", "Jho'vira", "Ossqarr"},
	[]string{"Fyrzorr", "Fyr'zira", "Osstarr"},
	[]string{"Zvoss", "Z'vira", "Orrlarr"},
	[]string{"Grenzorr", "Gren'zira", "Ossqarr"},
	[]string{"Xitvoss", "Xit'vira", "Osstarr"},
	[]string{"Trokzorr", "Trok'zira", "Orrlarr"},
	[]string{"Kvoss", "K'vira", "Ossqarr"},
	[]string{"Volzorr", "Vol'zira", "Osstarr"},
	[]string{"Pvoss", "P'vira", "Orrlarr"},
	[]string{"Quizorr", "Qui'zira", "Ossqarr"},
	[]string{"Jovvoss", "Jov'vira", "Osstarr"},
	[]string{"Fzorr", "F'zira", "Orrlarr"},
	[]string{"Zalvoss", "Zal'vira", "Ossqarr"},
	[]string{"Ghazorr", "Gha'zira", "Osstarr"},
	[]string{"Xorvoss", "Xor'vira", "Orrlarr"},
	[]string{"Thrazorr", "Thra'zira", "Ossqarr"},
	[]string{"Kozvoss", "Koz'vira", "Osstarr"},
	[]string{"Vzorr", "V'zira", "Orrlarr"},
	[]string{"Phenzorr", "Phen'zira", "Ossqarr"},
	[]string{"Qzorr", "Q'zira", "Osstarr"},
	[]string{"Jhalvoss", "Jhal'vira", "Orrlarr"},
	[]string{"Fyrzorr", "Fyr'zira", "Ossqarr"},
	[]string{"Zzorr", "Z'zira", "Osstarr"},
	[]string{"Gralvoss", "Gral'vira", "Orrlarr"},
	[]string{"Xanzorr", "Xan'zira", "Ossqarr"},
	[]string{"Thulvoss", "Thul'vira", "Osstarr"},
	[]string{"Kzorr", "K'zira", "Orrlarr"},
	[]string{"Vorvoss", "Vor'vira", "Ossqarr"},
	[]string{"Plozorr", "Plo'zira", "Osstarr"},
	[]string{"Quorvoss", "Quor'vira", "Orrlarr"},
	[]string{"Jyzorr", "Jy'zira", "Ossqarr"},
	[]string{"Floxvoss", "Flox'vira", "Osstarr"},
	[]string{"Zorzorr", "Zor'zira", "Orrlarr"},
	[]string{"Graxvoss", "Grax'vira", "Ossqarr"},
	[]string{"Xylzorr", "Xyl'zira", "Osstarr"},
	[]string{"Thrakvoss", "Thrak'vira", "Orrlarr"},
	[]string{"Kvoss", "K'vira", "Ossqarr"},
	[]string{"Vogzorr", "Vog'zira", "Osstarr"},
	[]string{"Pvoss", "P'vira", "Orrlarr"},
	[]string{"Quibzorr", "Quib'zira", "Ossqarr"},
	[]string{"Jaxvoss", "Jax'vira", "Osstarr"},
	[]string{"Fynzorr", "Fyn'zira", "Orrlarr"},
	[]string{"Zulvoss", "Zul'vira", "Ossqarr"},
	[]string{"Grikzorr", "Grik'zira", "Osstarr"},
	[]string{"Xevoss", "Xe'vira", "Orrlarr"},
	[]string{"Thulzorr", "Thul'zira", "Ossqarr"},
	[]string{"Krazvoss", "Kraz'vira", "Osstarr"},
	[]string{"Voszorr", "Vos'zira", "Orrlarr"},
	[]string{"Pryvoss", "Pry'vira", "Ossqarr"},
	[]string{"Qvoss", "Q'vira", "Osstarr"},
	[]string{"Jhozorr", "Jho'zira", "Orrlarr"},
	[]string{"Fyrvoss", "Fyr'vira", "Ossqarr"},
	[]string{"Zvoss", "Z'vira", "Osstarr"},
	[]string{"Grenvoss", "Gren'vira", "Orrlarr"},
	[]string{"Xitzorr", "Xit'zira", "Ossqarr"},
	[]string{"Trokvoss", "Trok'vira", "Osstarr"},
	[]string{"Kzorr", "K'zira", "Orrlarr"},
	[]string{"Volvoss", "Vol'vira", "Ossqarr"},
	[]string{"Pzorr", "P'zira", "Osstarr"},
	[]string{"Quivoss", "Qui'vira", "Orrlarr"},
	[]string{"Jovzorr", "Jov'zira", "Ossqarr"},
	[]string{"Fvoss", "F'vira", "Osstarr"},
	[]string{"Zalzorr", "Zal'zira", "Orrlarr"},
	[]string{"Ghavoss", "Gha'vira", "Ossqarr"},
	[]string{"Xorzorr", "Xor'zira", "Osstarr"},
	[]string{"Thravoss", "Thra'vira", "Orrlarr"},
	[]string{"Kozzorr", "Koz'zira", "Ossqarr"},
	[]string{"Vzorr", "V'zira", "Osstarr"},
	[]string{"Phenzorr", "Phen'zira", "Orrlarr"},
	[]string{"Qzorr", "Q'zira", "Ossqarr"},
	[]string{"Jhalvoss", "Jhal'vira", "Osstarr"},
	[]string{"Fyrzorr", "Fyr'zira", "Orrlarr"},
	[]string{"Zzorr", "Z'zira", "Osstarr"},
	[]string{"Gralvoss", "Gral'vira", "Orrlarr"},
	[]string{"Xanzorr", "Xan'zira", "Osstarr"},
	[]string{"Thulvoss", "Thul'vira", "Orrlarr"},
	[]string{"Kvoss", "K'vira", "Ossqarr"},
	[]string{"Vorzorr", "Vor'zira", "Osstarr"},
	[]string{"Plovoss", "Plo'vira", "Orrlarr"},
	[]string{"Quorzorr", "Quor'zira", "Ossqarr"},
	[]string{"Jyvoss", "Jy'vira", "Osstarr"},
	[]string{"Floxzorr", "Flox'zira", "Orrlarr"},
	[]string{"Zorvoss", "Zor'vira", "Osstarr"},
	[]string{"Graxzorr", "Grax'zira", "Osstarr"},
	[]string{"Xylvoss", "Xyl'vira", "Orrlarr"},
	[]string{"Thrakzorr", "Thrak'zira", "Ossqarr"},
	[]string{"Kzorr", "K'zira", "Osstarr"},
	[]string{"Vogvoss", "Vog'vira", "Orrlarr"},
	[]string{"Pzorr", "P'zira", "Ossqarr"},
	[]string{"Quibvoss", "Quib'vira", "Osstarr"},
	[]string{"Jaxzorr", "Jax'zira", "Orrlarr"},
	[]string{"Fynvoss", "Fyn'vira", "Ossqarr"},
	[]string{"Zulzorr", "Zul'zira", "Osstarr"},
	[]string{"Grikvoss", "Grik'vira", "Orrlarr"},
	[]string{"Xezorr", "Xe'zira", "Ossqarr"},
	[]string{"Thulzorr", "Thul'zira", "Osstarr"},
	[]string{"Krazvoss", "Kraz'vira", "Orrlarr"},
	[]string{"Voszorr", "Vos'zira", "Ossqarr"},
	[]string{"Pryvoss", "Pry'vira", "Osstarr"},
	[]string{"Qzorr", "Q'zira", "Orrlarr"},
	[]string{"Jhovoss", "Jho'vira", "Ossqarr"},
	[]string{"Fyrzorr", "Fyr'zira", "Osstarr"},
	[]string{"Zvoss", "Z'vira", "Orrlarr"},
	[]string{"Grenzorr", "Gren'zira", "Ossqarr"},
	[]string{"Xitvoss", "Xit'vira", "Osstarr"},
	[]string{"Trokzorr", "Trok'zira", "Orrlarr"},
	[]string{"Kvoss", "K'vira", "Ossqarr"},
	[]string{"Volzorr", "Vol'zira", "Osstarr"},
	[]string{"Pvoss", "P'vira", "Orrlarr"},
	[]string{"Quizorr", "Qui'zira", "Ossqarr"},
	[]string{"Jovvoss", "Jov'vira", "Osstarr"},
	[]string{"Fzorr", "F'zira", "Orrlarr"},
	[]string{"Zalvoss", "Zal'vira", "Ossqarr"},
	[]string{"Ghazorr", "Gha'zira", "Osstarr"},
	[]string{"Xorvoss", "Xor'vira", "Orrlarr"},
	[]string{"Thrazorr", "Thra'zira", "Ossqarr"},
	[]string{"Kozvoss", "Koz'vira", "Osstarr"},
	[]string{"Vzorr", "V'zira", "Orrlarr"},
	[]string{"Phenzorr", "Phen'zira", "Ossqarr"},
	[]string{"Qzorr", "Q'zira", "Osstarr"},
	[]string{"Jhalvoss", "Jhal'vira", "Orrlarr"},
	[]string{"Fyrzorr", "Fyr'zira", "Ossqarr"},
	[]string{"Zzorr", "Z'zira", "Osstarr"},
	[]string{"Gralvoss", "Gral'vira", "Orrlarr"},
	[]string{"Xanzorr", "Xan'zira", "Ossqarr"},
	[]string{"Thulvoss", "Thul'vira", "Osstarr"},
	[]string{"Kzorr", "K'zira", "Orrlarr"},
	[]string{"Vorvoss", "Vor'vira", "Ossqarr"},
	[]string{"Plozorr", "Plo'zira", "Osstarr"},
	[]string{"Quorvoss", "Quor'vira", "Orrlarr"},
	[]string{"Jyzorr", "Jy'zira", "Ossqarr"},
	[]string{"Floxvoss", "Flox'vira", "Osstarr"},
	[]string{"Zorzorr", "Zor'zira", "Orrlarr"},
	[]string{"Graxvoss", "Grax'vira", "Ossqarr"},
	[]string{"Xylzorr", "Xyl'zira", "Osstarr"},
	[]string{"Thrakvoss", "Thrak'vira", "Orrlarr"},
	[]string{"Kvoss", "K'vira", "Ossqarr"},
	[]string{"Vogzorr", "Vog'zira", "Osstarr"},
	[]string{"Pvoss", "P'vira", "Orrlarr"},
	[]string{"Quibzorr", "Quib'zira", "Ossqarr"},
	[]string{"Jaxvoss", "Jax'vira", "Osstarr"},
	[]string{"Fynzorr", "Fyn'zira", "Orrlarr"},
	[]string{"Zulvoss", "Zul'vira", "Ossqarr"},
	[]string{"Grikzorr", "Grik'zira", "Osstarr"},
	[]string{"Xevoss", "Xe'vira", "Orrlarr"},
	[]string{"Thulzorr", "Thul'zira", "Ossqarr"},
	[]string{"Krazvoss", "Kraz'vira", "Osstarr"},
	[]string{"Voszorr", "Vos'zira", "Ossqarr"},
	[]string{"Pryvoss", "Pry'vira", "Orrlarr"},
	[]string{"Qvoss", "Q'vira", "Osstarr"},
	[]string{"Jhozorr", "Jho'zira", "Orrlarr"},
	[]string{"Fyrvoss", "Fyr'vira", "Ossqarr"},
	[]string{"Zvoss", "Z'vira", "Osstarr"},
	[]string{"Grenvoss", "Gren'vira", "Orrlarr"},
	[]string{"Xitzorr", "Xit'zira", "Ossqarr"},
	[]string{"Trokvoss", "Trok'vira", "Osstarr"},
	[]string{"Kzorr", "K'zira", "Orrlarr"},
	[]string{"Volvoss", "Vol'vira", "Ossqarr"},
	[]string{"Pzorr", "P'zira", "Osstarr"},
	[]string{"Quivoss", "Qui'vira", "Orrlarr"},
	[]string{"Jovzorr", "Jov'zira", "Ossqarr"},
	[]string{"Fvoss", "F'vira", "Osstarr"},
	[]string{"Zalzorr", "Zal'zira", "Orrlarr"},
	[]string{"Ghavoss", "Gha'vira", "Ossqarr"},
	[]string{"Xorzorr", "Xor'zira", "Osstarr"},
	[]string{"Thravoss", "Thra'vira", "Orrlarr"},
	[]string{"Kozzorr", "Koz'zira", "Ossqarr"},
	[]string{"Vzorr", "V'zira", "Osstarr"},
	[]string{"Phenzorr", "Phen'zira", "Orrlarr"},
	[]string{"Qzorr", "Q'zira", "Ossqarr"},
	[]string{"Jhalvoss", "Jhal'vira", "Osstarr"},
	[]string{"Fyrzorr", "Fyr'zira", "Orrlarr"},
}

func PrintMap(index int) {
	s := "func RandomMaleName() string {" + "\n"
	s += "names := make(map[string]bool)" + "\n"
	for _, names := range Lists {
		s += fmt.Sprintf(`names["%v"] = true`, names[index]) + "\n"
	}

	s += "nameByIndex := make(map[int]string)" + "\n"
	s += "for k := range names {" + "\n"
	s += "	nameByIndex[len(nameByIndex)] = k" + "\n"
	s += "}" + "\n"
	s += "l := len(nameByIndex)" + "\n"
	s += `return nameByIndex[dice.NewDicepool().Sum(fmt.Sprintf("1d%v", l))-1]` + "\n"
	s += "}" + "\n"
	fmt.Println(s)
}
func RandomMaleName() string {
	names := make(map[string]bool)
	names["Kaelian"] = true
	names["Darian"] = true
	names["Torin"] = true
	names["Zevran"] = true
	names["Kaelen"] = true
	names["Cassian"] = true
	names["Jaxar"] = true
	names["Lorian"] = true
	names["Orion"] = true
	names["Zander"] = true
	names["Rhydian"] = true
	names["Soren"] = true
	names["Kaelum"] = true
	names["Jovan"] = true
	names["Daxos"] = true
	names["Torven"] = true
	names["Lysander"] = true
	names["Zarek"] = true
	names["Cyprian"] = true
	names["Kaelor"] = true
	names["Phelan"] = true
	names["Tavian"] = true
	names["Orin"] = true
	names["Zenon"] = true
	names["Kaelis"] = true
	names["Darien"] = true
	names["Jarek"] = true
	names["Lucien"] = true
	names["Zephyr"] = true
	names["Kaelan"] = true
	names["Rhys"] = true
	names["Sylas"] = true
	names["Toril"] = true
	names["Varian"] = true
	names["Xander"] = true
	names["Yorin"] = true
	names["Zale"] = true
	names["Kaelius"] = true
	names["Dax"] = true
	names["Jorin"] = true
	names["Lykos"] = true
	names["Nyx"] = true
	names["Osian"] = true
	names["Pryderi"] = true
	names["Quillon"] = true
	names["Rurik"] = true
	names["Saelen"] = true
	names["Talon"] = true
	names["Ulric"] = true
	names["Kaelos"] = true
	names["Dagan"] = true
	names["Jett"] = true
	names["Korbin"] = true
	names["Linden"] = true
	names["Maddox"] = true
	names["Nash"] = true
	names["Oberon"] = true
	names["Pax"] = true
	names["Quade"] = true
	names["Ridge"] = true
	names["Shea"] = true
	names["Trent"] = true
	names["Vance"] = true
	names["Wells"] = true
	names["Xeno"] = true
	names["York"] = true
	names["Zeke"] = true
	names["Kaelen"] = true
	names["Arvid"] = true
	names["Bastian"] = true
	names["Cedric"] = true
	names["Dmitri"] = true
	names["Eldon"] = true
	names["Fintan"] = true
	names["Gareth"] = true
	names["Harlan"] = true
	names["Ivan"] = true
	names["Jules"] = true
	names["Kael"] = true
	names["Leif"] = true
	names["Milo"] = true
	names["Nils"] = true
	names["Odin"] = true
	names["Peri"] = true
	names["Quill"] = true
	names["Rune"] = true
	names["Stig"] = true
	names["Sven"] = true
	names["Tygo"] = true
	names["Ulf"] = true
	names["Viggo"] = true
	names["Walt"] = true
	names["Xerxes"] = true
	names["Yale"] = true
	names["Zane"] = true
	names["Kael"] = true
	names["Bram"] = true
	names["Cai"] = true
	names["Draco"] = true
	names["Eros"] = true
	names["Faron"] = true
	names["Gideon"] = true
	names["Hector"] = true
	names["Icarus"] = true
	names["Juno"] = true
	names["Kratos"] = true
	names["Leo"] = true
	names["Mars"] = true
	names["Nemo"] = true
	names["Odin"] = true
	names["Pluto"] = true
	names["Quasar"] = true
	names["Rigel"] = true
	names["Sol"] = true
	names["Titan"] = true
	names["Ulysses"] = true
	names["Vulcan"] = true
	names["Wolf"] = true
	names["Xerxes"] = true
	names["Ymir"] = true
	names["Zagan"] = true
	names["Kael"] = true
	names["Aeson"] = true
	names["Beron"] = true
	names["Ceron"] = true
	names["Deron"] = true
	names["Eron"] = true
	names["Ferox"] = true
	names["Gerox"] = true
	names["Heron"] = true
	names["Irox"] = true
	names["Jeron"] = true
	names["Keron"] = true
	names["Leron"] = true
	names["Meron"] = true
	names["Neron"] = true
	names["Oeron"] = true
	names["Peron"] = true
	names["Qeron"] = true
	names["Reron"] = true
	names["Seron"] = true
	names["Terox"] = true
	names["Uron"] = true
	names["Varon"] = true
	names["Weron"] = true
	names["Xeron"] = true
	names["Yeron"] = true
	names["Zeron"] = true
	names["Kael"] = true
	names["Aion"] = true
	names["Bion"] = true
	names["Cion"] = true
	names["Dion"] = true
	names["Eion"] = true
	names["Fion"] = true
	names["Gion"] = true
	names["Hion"] = true
	names["Iion"] = true
	names["Jion"] = true
	names["Kion"] = true
	names["Lion"] = true
	names["Mion"] = true
	names["Nion"] = true
	names["Oion"] = true
	names["Pion"] = true
	names["Qion"] = true
	names["Rion"] = true
	names["Sion"] = true
	names["Tion"] = true
	names["Uion"] = true
	names["Vion"] = true
	names["Wion"] = true
	names["Xion"] = true
	names["Yion"] = true
	names["Zion"] = true
	names["Kael"] = true
	names["Corbin"] = true
	names["Draxon"] = true
	names["Ezran"] = true
	names["Fynne"] = true
	names["Gryff"] = true
	names["Jett"] = true
	names["Kael"] = true
	names["Lyr"] = true
	names["Mace"] = true
	names["Nyx"] = true
	names["Orin"] = true
	names["Pax"] = true
	names["Quinn"] = true
	names["Rook"] = true
	names["Sage"] = true
	names["Talon"] = true
	names["Vale"] = true
	names["Wren"] = true
	names["Xander"] = true
	names["York"] = true
	names["Zane"] = true
	names["Kael"] = true
	names["Bane"] = true
	names["Cade"] = true
	names["Dane"] = true
	names["Egan"] = true
	names["Finn"] = true
	names["Gage"] = true
	names["Hale"] = true
	names["Ivan"] = true
	names["Jace"] = true
	names["Kobe"] = true
	names["Lane"] = true
	names["Mace"] = true
	names["Nate"] = true
	names["Owen"] = true
	names["Pierce"] = true
	names["Quade"] = true
	names["Reed"] = true
	names["Shade"] = true
	names["Troy"] = true
	names["Vance"] = true
	names["Wade"] = true
	names["Xavier"] = true
	names["Yale"] = true
	names["Zeke"] = true
	names["Kael"] = true
	names["Arlo"] = true
	names["Brio"] = true
	names["Cairo"] = true
	names["Dario"] = true
	names["Elio"] = true
	names["Fabian"] = true
	names["Gian"] = true
	names["Hugo"] = true
	names["Ivo"] = true
	names["Jairo"] = true
	names["Kaito"] = true
	names["Leo"] = true
	names["Marco"] = true
	names["Nico"] = true
	names["Orio"] = true
	names["Pablo"] = true
	names["Rio"] = true
	names["Silas"] = true
	names["Theo"] = true
	names["Vigo"] = true
	names["Wesley"] = true
	names["Xavi"] = true
	names["Yves"] = true
	names["Zion"] = true
	names["Kael"] = true
	names["Ash"] = true
	names["Blaze"] = true
	names["Clay"] = true
	names["Dust"] = true
	names["Echo"] = true
	names["Flame"] = true
	names["Gale"] = true
	names["Haze"] = true
	names["Ice"] = true
	names["Jet"] = true
	names["Knight"] = true
	names["Lake"] = true
	names["Mist"] = true
	names["North"] = true
	names["Petal"] = true
	names["Quartz"] = true
	names["Rust"] = true
	names["Sky"] = true
	names["Stone"] = true
	names["Thorn"] = true
	names["Umbra"] = true
	names["Vapor"] = true
	names["Wave"] = true
	names["Yarn"] = true
	names["Zenith"] = true
	names["Kael"] = true
	names["Apex"] = true
	names["Bluff"] = true
	names["Cliff"] = true
	names["Crag"] = true
	names["Drift"] = true
	names["Edge"] = true
	names["Fjord"] = true
	names["Gorge"] = true
	names["Hill"] = true
	names["Knoll"] = true
	names["Ledge"] = true
	names["Mesa"] = true
	names["Peak"] = true
	names["Ridge"] = true
	names["Spire"] = true
	names["Summit"] = true
	names["Tor"] = true
	names["Butte"] = true
	names["Dune"] = true
	names["Vale"] = true
	names["Wold"] = true
	names["Bluff"] = true
	names["Brow"] = true
	names["Crest"] = true
	names["Nose"] = true
	names["Spur"] = true
	names["Berm"] = true
	names["Bank"] = true
	names["Barrow"] = true
	names["Cairn"] = true
	names["Delta"] = true
	names["Dome"] = true
	names["Esker"] = true
	names["Finger"] = true
	names["Hogback"] = true
	names["Hummock"] = true
	names["Kame"] = true
	names["Knob"] = true
	names["Monadnock"] = true
	names["Motte"] = true
	names["Outcrop"] = true
	names["Pingo"] = true
	names["Pyramid"] = true
	names["Shoal"] = true
	names["Teardrop"] = true
	names["Uvala"] = true
	names["Ventifact"] = true
	names["Waterfall"] = true
	names["Yazoo"] = true
	names["Zibar"] = true
	names["Kael"] = true
	names["Arch"] = true
	names["Bend"] = true
	names["Coil"] = true
	names["Curve"] = true
	names["Fold"] = true
	names["Hairpin"] = true
	names["Helix"] = true
	names["Loop"] = true
	names["Meander"] = true
	names["Oxbow"] = true
	names["Switchback"] = true
	names["Traverse"] = true
	names["Twist"] = true
	names["Whorl"] = true
	names["Zigzag"] = true
	names["Kael"] = true
	names["Male_Name"] = true
	names["Kaelian"] = true
	names["Darian"] = true
	names["Torin"] = true
	names["Thragg"] = true
	names["Kztak"] = true
	names["Vorlag"] = true
	names["Ploov"] = true
	names["Quorrin"] = true
	names["Jylys"] = true
	names["Floxx"] = true
	names["Zxulan"] = true
	names["Gorthun"] = true
	names["Xanthur"] = true
	names["Trog"] = true
	names["Klatho"] = true
	names["Vortan"] = true
	names["Pkarr"] = true
	names["Quorgil"] = true
	names["Jhastar"] = true
	names["Fnoor"] = true
	names["Zulgarn"] = true
	names["Grikk"] = true
	names["Xevar"] = true
	names["Ban"] = true
	names["Krazak"] = true
	names["Vossk"] = true
	names["Pryxx"] = true
	names["Qzan"] = true
	names["Jaxom"] = true
	names["Fyrdek"] = true
	names["Zborak"] = true
	names["Grendar"] = true
	names["Xithos"] = true
	names["Trokk"] = true
	names["Kvorn"] = true
	names["Volnix"] = true
	names["Ptalon"] = true
	names["Quibos"] = true
	names["Jovos"] = true
	names["Flint"] = true
	names["Zalanth"] = true
	names["Ghanal"] = true
	names["Xortic"] = true
	names["Thraxx"] = true
	names["Kozar"] = true
	names["Vkoss"] = true
	names["Phendor"] = true
	names["Qarth"] = true
	names["Jhalen"] = true
	names["Fyrgon"] = true
	names["Zvokk"] = true
	names["Gralnex"] = true
	names["Xandor"] = true
	names["Thulkor"] = true
	names["Kzann"] = true
	names["Vorqex"] = true
	names["Plonar"] = true
	names["Quordis"] = true
	names["Jyvoss"] = true
	names["Floxnar"] = true
	names["Zorqeth"] = true
	names["Graxill"] = true
	names["Xyloth"] = true
	names["Thrakonn"] = true
	names["Kvell"] = true
	names["Vognn"] = true
	names["Ptarr"] = true
	names["Quiblor"] = true
	names["Jaxonn"] = true
	names["Fynnar"] = true
	names["Zulqar"] = true
	names["Griklor"] = true
	names["Xevoss"] = true
	names["Thulmarr"] = true
	names["Krazikk"] = true
	names["Voskar"] = true
	names["Pryqex"] = true
	names["Qvarr"] = true
	names["Jhorak"] = true
	names["Fyrzann"] = true
	names["Zborr"] = true
	names["Grentek"] = true
	names["Xitharr"] = true
	names["Trokonn"] = true
	names["Kvorr"] = true
	names["Volqex"] = true
	names["Ptorr"] = true
	names["Quivoss"] = true
	names["Jovkarr"] = true
	names["Flarr"] = true
	names["Zalqor"] = true
	names["Ghavoss"] = true
	names["Xortall"] = true
	names["Thraqex"] = true
	names["Kozvarr"] = true
	names["Vkarr"] = true
	names["Phenqor"] = true
	names["Qzann"] = true
	names["Jhalkarr"] = true
	names["Fyrvoss"] = true
	names["Zvarr"] = true
	names["Gralqex"] = true
	names["Xanvoss"] = true
	names["Thulqor"] = true
	names["Kzarr"] = true
	names["Vortall"] = true
	names["Ploqex"] = true
	names["Quorvoss"] = true
	names["Jyzarr"] = true
	names["Floxqor"] = true
	names["Zortall"] = true
	names["Graxqex"] = true
	names["Xylvoss"] = true
	names["Thrakzarr"] = true
	names["Kvarr"] = true
	names["Vogqor"] = true
	names["Ptall"] = true
	names["Quibvoss"] = true
	names["Jaxzarr"] = true
	names["Fynqor"] = true
	names["Zulvoss"] = true
	names["Grikzarr"] = true
	names["Xeqor"] = true
	names["Thulvoss"] = true
	names["Krazzarr"] = true
	names["Vosqor"] = true
	names["Pryvoss"] = true
	names["Qzorr"] = true
	names["Jhovoss"] = true
	names["Fyrzorr"] = true
	names["Zborr"] = true
	names["Grenvoss"] = true
	names["Xitzorr"] = true
	names["Trokvoss"] = true
	names["Kzorr"] = true
	names["Volvoss"] = true
	names["Pzorr"] = true
	names["Quivoss"] = true
	names["Jovzorr"] = true
	names["Fvoss"] = true
	names["Zalzorr"] = true
	names["Ghavoss"] = true
	names["Xorzorr"] = true
	names["Thravoss"] = true
	names["Kozzorr"] = true
	names["Vzorr"] = true
	names["Phenvoss"] = true
	names["Qzorr"] = true
	names["Jhalvoss"] = true
	names["Fyrzorr"] = true
	names["Zzorr"] = true
	names["Gralvoss"] = true
	names["Xanzorr"] = true
	names["Thulvoss"] = true
	names["Kvoss"] = true
	names["Vorzorr"] = true
	names["Plovoss"] = true
	names["Quorzorr"] = true
	names["Jyvoss"] = true
	names["Floxzorr"] = true
	names["Zorvoss"] = true
	names["Graxzorr"] = true
	names["Xylvoss"] = true
	names["Thrakzorr"] = true
	names["Kzorr"] = true
	names["Vogvoss"] = true
	names["Pzorr"] = true
	names["Quibvoss"] = true
	names["Jaxzorr"] = true
	names["Fynvoss"] = true
	names["Zulzorr"] = true
	names["Grikvoss"] = true
	names["Xezorr"] = true
	names["Thulzorr"] = true
	names["Krazvoss"] = true
	names["Voszorr"] = true
	names["Pryvoss"] = true
	names["Qzorr"] = true
	names["Jhovoss"] = true
	names["Fyrzorr"] = true
	names["Zvoss"] = true
	names["Grenzorr"] = true
	names["Xitvoss"] = true
	names["Trokzorr"] = true
	names["Kvoss"] = true
	names["Volzorr"] = true
	names["Pvoss"] = true
	names["Quizorr"] = true
	names["Jovvoss"] = true
	names["Fzorr"] = true
	names["Zalvoss"] = true
	names["Ghazorr"] = true
	names["Xorvoss"] = true
	names["Thrazorr"] = true
	names["Kozvoss"] = true
	names["Vzorr"] = true
	names["Phenzorr"] = true
	names["Qzorr"] = true
	names["Jhalvoss"] = true
	names["Fyrzorr"] = true
	names["Zzorr"] = true
	names["Gralvoss"] = true
	names["Xanzorr"] = true
	names["Thulvoss"] = true
	names["Kzorr"] = true
	names["Vorvoss"] = true
	names["Plozorr"] = true
	names["Quorvoss"] = true
	names["Jyzorr"] = true
	names["Floxvoss"] = true
	names["Zorzorr"] = true
	names["Graxvoss"] = true
	names["Xylzorr"] = true
	names["Thrakvoss"] = true
	names["Kvoss"] = true
	names["Vogzorr"] = true
	names["Pvoss"] = true
	names["Quibzorr"] = true
	names["Jaxvoss"] = true
	names["Fynzorr"] = true
	names["Zulvoss"] = true
	names["Grikzorr"] = true
	names["Xevoss"] = true
	names["Thulzorr"] = true
	names["Krazvoss"] = true
	names["Voszorr"] = true
	names["Pryvoss"] = true
	names["Qvoss"] = true
	names["Jhozorr"] = true
	names["Fyrvoss"] = true
	names["Zvoss"] = true
	names["Grenvoss"] = true
	names["Xitzorr"] = true
	names["Trokvoss"] = true
	names["Kzorr"] = true
	names["Volvoss"] = true
	names["Pzorr"] = true
	names["Quivoss"] = true
	names["Jovzorr"] = true
	names["Fvoss"] = true
	names["Zalzorr"] = true
	names["Ghavoss"] = true
	names["Xorzorr"] = true
	names["Thravoss"] = true
	names["Kozzorr"] = true
	names["Vzorr"] = true
	names["Phenzorr"] = true
	names["Qzorr"] = true
	names["Jhalvoss"] = true
	names["Fyrzorr"] = true
	names["Zzorr"] = true
	names["Gralvoss"] = true
	names["Xanzorr"] = true
	names["Thulvoss"] = true
	names["Kvoss"] = true
	names["Vorzorr"] = true
	names["Plovoss"] = true
	names["Quorzorr"] = true
	names["Jyvoss"] = true
	names["Floxzorr"] = true
	names["Zorvoss"] = true
	names["Graxzorr"] = true
	names["Xylvoss"] = true
	names["Thrakzorr"] = true
	names["Kzorr"] = true
	names["Vogvoss"] = true
	names["Pzorr"] = true
	names["Quibvoss"] = true
	names["Jaxzorr"] = true
	names["Fynvoss"] = true
	names["Zulzorr"] = true
	names["Grikvoss"] = true
	names["Xezorr"] = true
	names["Thulzorr"] = true
	names["Krazvoss"] = true
	names["Voszorr"] = true
	names["Pryvoss"] = true
	names["Qzorr"] = true
	names["Jhovoss"] = true
	names["Fyrzorr"] = true
	names["Zvoss"] = true
	names["Grenzorr"] = true
	names["Xitvoss"] = true
	names["Trokzorr"] = true
	names["Kvoss"] = true
	names["Volzorr"] = true
	names["Pvoss"] = true
	names["Quizorr"] = true
	names["Jovvoss"] = true
	names["Fzorr"] = true
	names["Zalvoss"] = true
	names["Ghazorr"] = true
	names["Xorvoss"] = true
	names["Thrazorr"] = true
	names["Kozvoss"] = true
	names["Vzorr"] = true
	names["Phenzorr"] = true
	names["Qzorr"] = true
	names["Jhalvoss"] = true
	names["Fyrzorr"] = true
	names["Zzorr"] = true
	names["Gralvoss"] = true
	names["Xanzorr"] = true
	names["Thulvoss"] = true
	names["Kzorr"] = true
	names["Vorvoss"] = true
	names["Plozorr"] = true
	names["Quorvoss"] = true
	names["Jyzorr"] = true
	names["Floxvoss"] = true
	names["Zorzorr"] = true
	names["Graxvoss"] = true
	names["Xylzorr"] = true
	names["Thrakvoss"] = true
	names["Kvoss"] = true
	names["Vogzorr"] = true
	names["Pvoss"] = true
	names["Quibzorr"] = true
	names["Jaxvoss"] = true
	names["Fynzorr"] = true
	names["Zulvoss"] = true
	names["Grikzorr"] = true
	names["Xevoss"] = true
	names["Thulzorr"] = true
	names["Krazvoss"] = true
	names["Voszorr"] = true
	names["Pryvoss"] = true
	names["Qvoss"] = true
	names["Jhozorr"] = true
	names["Fyrvoss"] = true
	names["Zvoss"] = true
	names["Grenvoss"] = true
	names["Xitzorr"] = true
	names["Trokvoss"] = true
	names["Kzorr"] = true
	names["Volvoss"] = true
	names["Pzorr"] = true
	names["Quivoss"] = true
	names["Jovzorr"] = true
	names["Fvoss"] = true
	names["Zalzorr"] = true
	names["Ghavoss"] = true
	names["Xorzorr"] = true
	names["Thravoss"] = true
	names["Kozzorr"] = true
	names["Vzorr"] = true
	names["Phenzorr"] = true
	names["Qzorr"] = true
	names["Jhalvoss"] = true
	names["Fyrzorr"] = true
	nameByIndex := make(map[int]string)
	for k := range names {
		nameByIndex[len(nameByIndex)] = k
	}
	l := len(nameByIndex)
	return nameByIndex[dice.NewDicepool().Sum(fmt.Sprintf("1d%v", l))-1]
}

func RandomFemaleName() string {
	names := make(map[string]bool)
	names["Zorya"] = true
	names["Elara"] = true
	names["Lyra"] = true
	names["Seren"] = true
	names["Nyx"] = true
	names["Elysia"] = true
	names["Isolde"] = true
	names["Thalia"] = true
	names["Aurora"] = true
	names["Cyra"] = true
	names["Maia"] = true
	names["Lumina"] = true
	names["Theia"] = true
	names["Elara"] = true
	names["Nerys"] = true
	names["Anya"] = true
	names["Valeria"] = true
	names["Helene"] = true
	names["Selene"] = true
	names["Ione"] = true
	names["Calista"] = true
	names["Elara"] = true
	names["Seraphina"] = true
	names["Cygnus"] = true
	names["Lyric"] = true
	names["Cassiopeia"] = true
	names["Andromeda"] = true
	names["Eos"] = true
	names["Belinda"] = true
	names["Nova"] = true
	names["Elara"] = true
	names["Ophelia"] = true
	names["Persephone"] = true
	names["Artemis"] = true
	names["Calliope"] = true
	names["Lilith"] = true
	names["Morrigan"] = true
	names["Eirian"] = true
	names["Lunara"] = true
	names["Melusine"] = true
	names["Sirius"] = true
	names["Terra"] = true
	names["Vega"] = true
	names["Rhea"] = true
	names["Solana"] = true
	names["Umbra"] = true
	names["Willow"] = true
	names["Yvaine"] = true
	names["Zinnia"] = true
	names["Astra"] = true
	names["Briar"] = true
	names["Clover"] = true
	names["Dahlia"] = true
	names["Flora"] = true
	names["Gaia"] = true
	names["Hazel"] = true
	names["Iris"] = true
	names["Jasmine"] = true
	names["Kestra"] = true
	names["Laurel"] = true
	names["Magnolia"] = true
	names["Olive"] = true
	names["Petra"] = true
	names["Rose"] = true
	names["Sage"] = true
	names["Tansy"] = true
	names["Veronica"] = true
	names["Wisteria"] = true
	names["Acacia"] = true
	names["Amber"] = true
	names["Azalea"] = true
	names["Blossom"] = true
	names["Camellia"] = true
	names["Chrys"] = true
	names["Daphne"] = true
	names["Ember"] = true
	names["Faye"] = true
	names["Ginger"] = true
	names["Glynn"] = true
	names["Holly"] = true
	names["Indigo"] = true
	names["Jewel"] = true
	names["Kalina"] = true
	names["Lark"] = true
	names["Marigold"] = true
	names["Meadow"] = true
	names["Nectar"] = true
	names["Orchid"] = true
	names["Peony"] = true
	names["Quinn"] = true
	names["Rain"] = true
	names["Saffron"] = true
	names["Sunny"] = true
	names["Tansy"] = true
	names["Violet"] = true
	names["Tansy"] = true
	names["Alba"] = true
	names["Beta"] = true
	names["Calypso"] = true
	names["Delta"] = true
	names["Echo"] = true
	names["Gemini"] = true
	names["Hera"] = true
	names["Io"] = true
	names["Jupiter"] = true
	names["Luna"] = true
	names["Lyra"] = true
	names["Maia"] = true
	names["Mars"] = true
	names["Mira"] = true
	names["Nix"] = true
	names["Oberon"] = true
	names["Pandora"] = true
	names["Rhea"] = true
	names["Selene"] = true
	names["Tethys"] = true
	names["Thebe"] = true
	names["Venus"] = true
	names["Vesta"] = true
	names["Yara"] = true
	names["Ziva"] = true
	names["Zora"] = true
	names["Aelia"] = true
	names["Ania"] = true
	names["Basia"] = true
	names["Celia"] = true
	names["Dacia"] = true
	names["Eira"] = true
	names["Fabia"] = true
	names["Galia"] = true
	names["Helvia"] = true
	names["Ilia"] = true
	names["Justa"] = true
	names["Livia"] = true
	names["Maia"] = true
	names["Nerva"] = true
	names["Octa"] = true
	names["Paula"] = true
	names["Quinta"] = true
	names["Rufina"] = true
	names["Secunda"] = true
	names["Tertia"] = true
	names["Urbana"] = true
	names["Valeria"] = true
	names["Vibia"] = true
	names["Xenia"] = true
	names["Yuva"] = true
	names["Zosia"] = true
	names["Zanna"] = true
	names["Alta"] = true
	names["Beta"] = true
	names["Cyma"] = true
	names["Delta"] = true
	names["Eira"] = true
	names["Flux"] = true
	names["Gamma"] = true
	names["Helia"] = true
	names["Iota"] = true
	names["Jora"] = true
	names["Kappa"] = true
	names["Lambda"] = true
	names["Mu"] = true
	names["Nu"] = true
	names["Omicron"] = true
	names["Pi"] = true
	names["Qora"] = true
	names["Rho"] = true
	names["Sigma"] = true
	names["Tau"] = true
	names["Upsilon"] = true
	names["Phi"] = true
	names["Chi"] = true
	names["Psi"] = true
	names["Omega"] = true
	names["Alpha"] = true
	names["Astra"] = true
	names["Lyra"] = true
	names["Nova"] = true
	names["Solara"] = true
	names["Cyane"] = true
	names["Lunara"] = true
	names["Zorya"] = true
	names["Rhea"] = true
	names["Celeste"] = true
	names["Andra"] = true
	names["Elara"] = true
	names["Seren"] = true
	names["Thalia"] = true
	names["Eos"] = true
	names["Aurora"] = true
	names["Maia"] = true
	names["Nyx"] = true
	names["Theia"] = true
	names["Selene"] = true
	names["Lumina"] = true
	names["Ione"] = true
	names["Calista"] = true
	names["Anya"] = true
	names["Belinda"] = true
	names["Cassiopeia"] = true
	names["Elara"] = true
	names["Helene"] = true
	names["Isolde"] = true
	names["Melusine"] = true
	names["Ophelia"] = true
	names["Persephone"] = true
	names["Artemis"] = true
	names["Calliope"] = true
	names["Morrigan"] = true
	names["Nova"] = true
	names["Willow"] = true
	names["Yvaine"] = true
	names["Zinnia"] = true
	names["Astra"] = true
	names["Briar"] = true
	names["Clover"] = true
	names["Dahlia"] = true
	names["Flora"] = true
	names["Gaia"] = true
	names["Hazel"] = true
	names["Iris"] = true
	names["Jasmine"] = true
	names["Laurel"] = true
	names["Magnolia"] = true
	names["Olive"] = true
	names["Petra"] = true
	names["Rose"] = true
	names["Sage"] = true
	names["Tansy"] = true
	names["Veronica"] = true
	names["Wisteria"] = true
	names["Acacia"] = true
	names["Amber"] = true
	names["Azalea"] = true
	names["Blossom"] = true
	names["Camellia"] = true
	names["Chrys"] = true
	names["Daphne"] = true
	names["Ember"] = true
	names["Faye"] = true
	names["Ginger"] = true
	names["Holly"] = true
	names["Indigo"] = true
	names["Jewel"] = true
	names["Kalina"] = true
	names["Lark"] = true
	names["Marigold"] = true
	names["Meadow"] = true
	names["Nectar"] = true
	names["Orchid"] = true
	names["Peony"] = true
	names["Quinn"] = true
	names["Rain"] = true
	names["Saffron"] = true
	names["Sunny"] = true
	names["Tansy"] = true
	names["Violet"] = true
	names["Alba"] = true
	names["Beta"] = true
	names["Calypso"] = true
	names["Delta"] = true
	names["Echo"] = true
	names["Gemini"] = true
	names["Hera"] = true
	names["Io"] = true
	names["Jupiter"] = true
	names["Luna"] = true
	names["Mars"] = true
	names["Mira"] = true
	names["Nix"] = true
	names["Oberon"] = true
	names["Pandora"] = true
	names["Rhea"] = true
	names["Selene"] = true
	names["Tethys"] = true
	names["Thebe"] = true
	names["Venus"] = true
	names["Vesta"] = true
	names["Yara"] = true
	names["Ziva"] = true
	names["Zora"] = true
	names["Aelia"] = true
	names["Ania"] = true
	names["Basia"] = true
	names["Celia"] = true
	names["Dacia"] = true
	names["Eira"] = true
	names["Fabia"] = true
	names["Galia"] = true
	names["Helvia"] = true
	names["Ilia"] = true
	names["Justa"] = true
	names["Livia"] = true
	names["Maia"] = true
	names["Nerva"] = true
	names["Octa"] = true
	names["Paula"] = true
	names["Quinta"] = true
	names["Rufina"] = true
	names["Secunda"] = true
	names["Tertia"] = true
	names["Urbana"] = true
	names["Valeria"] = true
	names["Vibia"] = true
	names["Xenia"] = true
	names["Yuva"] = true
	names["Zosia"] = true
	names["Zanna"] = true
	names["Alta"] = true
	names["Beta"] = true
	names["Cyma"] = true
	names["Delta"] = true
	names["Eira"] = true
	names["Flux"] = true
	names["Gamma"] = true
	names["Helia"] = true
	names["Iota"] = true
	names["Jora"] = true
	names["Kappa"] = true
	names["Lambda"] = true
	names["Mu"] = true
	names["Nu"] = true
	names["Omicron"] = true
	names["Pi"] = true
	names["Qora"] = true
	names["Rho"] = true
	names["Sigma"] = true
	names["Tau"] = true
	names["Upsilon"] = true
	names["Phi"] = true
	names["Chi"] = true
	names["Psi"] = true
	names["Omega"] = true
	names["Alpha"] = true
	names["Astra"] = true
	names["Lyra"] = true
	names["Nova"] = true
	names["Orion"] = true
	names["Solara"] = true
	names["Cyane"] = true
	names["Lunara"] = true
	names["Female_Name"] = true
	names["Zr'ella"] = true
	names["Grisha"] = true
	names["Xylia"] = true
	names["Thressa"] = true
	names["K'vira"] = true
	names["Vexxa"] = true
	names["Pliis"] = true
	names["Quessa"] = true
	names["Jyra"] = true
	names["Fleena"] = true
	names["Z'neera"] = true
	names["Grelda"] = true
	names["Xiara"] = true
	names["Trilla"] = true
	names["K'ressa"] = true
	names["Vyssa"] = true
	names["P'lina"] = true
	names["Quara"] = true
	names["Jhessa"] = true
	names["F'lissa"] = true
	names["Zara"] = true
	names["Grelia"] = true
	names["Xena"] = true
	names["Thia"] = true
	names["Krina"] = true
	names["Vera"] = true
	names["Priya"] = true
	names["Q'ora"] = true
	names["Jara"] = true
	names["Fyra"] = true
	names["Z'lena"] = true
	names["Grexa"] = true
	names["Xira"] = true
	names["Talia"] = true
	names["K'lena"] = true
	names["Volta"] = true
	names["P'thea"] = true
	names["Quila"] = true
	names["Jora"] = true
	names["F'lya"] = true
	names["Zara"] = true
	names["Gha'ra"] = true
	names["Xor'na"] = true
	names["Thora"] = true
	names["Kora"] = true
	names["V'nessa"] = true
	names["Phena"] = true
	names["Q'ira"] = true
	names["Jhaya"] = true
	names["Fyrra"] = true
	names["Z'vira"] = true
	names["Gralia"] = true
	names["Xan'tha"] = true
	names["Thul'ra"] = true
	names["K'zara"] = true
	names["Vor'na"] = true
	names["Plo'via"] = true
	names["Quor'la"] = true
	names["Jy'nessa"] = true
	names["Flox'ira"] = true
	names["Zor'lena"] = true
	names["Grax'na"] = true
	names["Xyl'ara"] = true
	names["Thrak'ea"] = true
	names["K'voss"] = true
	names["Vog'ira"] = true
	names["P'tess"] = true
	names["Quib'ra"] = true
	names["Jax'ira"] = true
	names["Fyn'essa"] = true
	names["Zul'tha"] = true
	names["Grik'na"] = true
	names["Xe'vira"] = true
	names["Thul'mia"] = true
	names["Kraz'na"] = true
	names["Vos'la"] = true
	names["Pry'nia"] = true
	names["Q'voss"] = true
	names["Jho'ra"] = true
	names["Fyr'zira"] = true
	names["Z'nessa"] = true
	names["Gren'ta"] = true
	names["Xit'hera"] = true
	names["Trok'na"] = true
	names["K'viss"] = true
	names["Vol'nia"] = true
	names["P'tara"] = true
	names["Qui'vira"] = true
	names["Jov'kess"] = true
	names["F'liss"] = true
	names["Zal'qia"] = true
	names["Gha'vira"] = true
	names["Xor'tess"] = true
	names["Thra'qia"] = true
	names["Koz'vess"] = true
	names["V'kess"] = true
	names["Phen'qia"] = true
	names["Q'zira"] = true
	names["Jhal'kess"] = true
	names["Fyr'vira"] = true
	names["Z'vess"] = true
	names["Gral'qia"] = true
	names["Xan'vira"] = true
	names["Thul'qia"] = true
	names["K'zess"] = true
	names["Vor'tess"] = true
	names["Plo'qia"] = true
	names["Quor'vira"] = true
	names["Jy'zess"] = true
	names["Flox'qia"] = true
	names["Zor'tess"] = true
	names["Grax'qia"] = true
	names["Xyl'vira"] = true
	names["Thrak'zess"] = true
	names["K'vess"] = true
	names["Vog'qia"] = true
	names["P'tess"] = true
	names["Quib'vira"] = true
	names["Jax'zess"] = true
	names["Fyn'qia"] = true
	names["Zul'vira"] = true
	names["Grik'zess"] = true
	names["Xe'qia"] = true
	names["Thul'vira"] = true
	names["Kraz'zess"] = true
	names["Vos'qia"] = true
	names["Pry'vira"] = true
	names["Q'zira"] = true
	names["Jho'vira"] = true
	names["Fyr'zira"] = true
	names["Z'vira"] = true
	names["Gren'vira"] = true
	names["Xit'zira"] = true
	names["Trok'vira"] = true
	names["K'zira"] = true
	names["Vol'vira"] = true
	names["P'zira"] = true
	names["Qui'vira"] = true
	names["Jov'zira"] = true
	names["F'vira"] = true
	names["Zal'zira"] = true
	names["Gha'vira"] = true
	names["Xor'zira"] = true
	names["Thra'vira"] = true
	names["Koz'zira"] = true
	names["V'zira"] = true
	names["Phen'vira"] = true
	names["Q'zira"] = true
	names["Jhal'vira"] = true
	names["Fyr'zira"] = true
	names["Z'zira"] = true
	names["Gral'vira"] = true
	names["Xan'zira"] = true
	names["Thul'vira"] = true
	names["K'vira"] = true
	names["Vor'zira"] = true
	names["Plo'vira"] = true
	names["Quor'zira"] = true
	names["Jy'vira"] = true
	names["Flox'zira"] = true
	names["Zor'vira"] = true
	names["Grax'zira"] = true
	names["Xyl'vira"] = true
	names["Thrak'zira"] = true
	names["K'zira"] = true
	names["Vog'vira"] = true
	names["P'zira"] = true
	names["Quib'vira"] = true
	names["Jax'zira"] = true
	names["Fyn'vira"] = true
	names["Zul'zira"] = true
	names["Grik'vira"] = true
	names["Xe'zira"] = true
	names["Thul'zira"] = true
	names["Kraz'vira"] = true
	names["Vos'zira"] = true
	names["Pry'vira"] = true
	names["Q'zira"] = true
	names["Jho'vira"] = true
	names["Fyr'zira"] = true
	names["Z'vira"] = true
	names["Gren'zira"] = true
	names["Xit'vira"] = true
	names["Trok'zira"] = true
	names["K'vira"] = true
	names["Vol'zira"] = true
	names["P'vira"] = true
	names["Qui'zira"] = true
	names["Jov'vira"] = true
	names["F'zira"] = true
	names["Zal'vira"] = true
	names["Gha'zira"] = true
	names["Xor'vira"] = true
	names["Thra'zira"] = true
	names["Koz'vira"] = true
	names["V'zira"] = true
	names["Phen'zira"] = true
	names["Q'zira"] = true
	names["Jhal'vira"] = true
	names["Fyr'zira"] = true
	names["Z'zira"] = true
	names["Gral'vira"] = true
	names["Xan'zira"] = true
	names["Thul'vira"] = true
	names["K'zira"] = true
	names["Vor'vira"] = true
	names["Plo'zira"] = true
	names["Quor'vira"] = true
	names["Jy'zira"] = true
	names["Flox'vira"] = true
	names["Zor'zira"] = true
	names["Grax'vira"] = true
	names["Xyl'zira"] = true
	names["Thrak'vira"] = true
	names["K'vira"] = true
	names["Vog'zira"] = true
	names["P'vira"] = true
	names["Quib'zira"] = true
	names["Jax'vira"] = true
	names["Fyn'zira"] = true
	names["Zul'vira"] = true
	names["Grik'zira"] = true
	names["Xe'vira"] = true
	names["Thul'zira"] = true
	names["Kraz'vira"] = true
	names["Vos'zira"] = true
	names["Pry'vira"] = true
	names["Q'vira"] = true
	names["Jho'zira"] = true
	names["Fyr'vira"] = true
	names["Z'vira"] = true
	names["Gren'vira"] = true
	names["Xit'zira"] = true
	names["Trok'vira"] = true
	names["K'zira"] = true
	names["Vol'vira"] = true
	names["P'zira"] = true
	names["Qui'vira"] = true
	names["Jov'zira"] = true
	names["F'vira"] = true
	names["Zal'zira"] = true
	names["Gha'vira"] = true
	names["Xor'zira"] = true
	names["Thra'vira"] = true
	names["Koz'zira"] = true
	names["V'zira"] = true
	names["Phen'zira"] = true
	names["Q'zira"] = true
	names["Jhal'vira"] = true
	names["Fyr'zira"] = true
	names["Z'zira"] = true
	names["Gral'vira"] = true
	names["Xan'zira"] = true
	names["Thul'vira"] = true
	names["K'vira"] = true
	names["Vor'zira"] = true
	names["Plo'vira"] = true
	names["Quor'zira"] = true
	names["Jy'vira"] = true
	names["Flox'zira"] = true
	names["Zor'vira"] = true
	names["Grax'zira"] = true
	names["Xyl'vira"] = true
	names["Thrak'zira"] = true
	names["K'zira"] = true
	names["Vog'vira"] = true
	names["P'zira"] = true
	names["Quib'vira"] = true
	names["Jax'zira"] = true
	names["Fyn'vira"] = true
	names["Zul'zira"] = true
	names["Grik'vira"] = true
	names["Xe'zira"] = true
	names["Thul'zira"] = true
	names["Kraz'vira"] = true
	names["Vos'zira"] = true
	names["Pry'vira"] = true
	names["Q'zira"] = true
	names["Jho'vira"] = true
	names["Fyr'zira"] = true
	names["Z'vira"] = true
	names["Gren'zira"] = true
	names["Xit'vira"] = true
	names["Trok'zira"] = true
	names["K'vira"] = true
	names["Vol'zira"] = true
	names["P'vira"] = true
	names["Qui'zira"] = true
	names["Jov'vira"] = true
	names["F'zira"] = true
	names["Zal'vira"] = true
	names["Gha'zira"] = true
	names["Xor'vira"] = true
	names["Thra'zira"] = true
	names["Koz'vira"] = true
	names["V'zira"] = true
	names["Phen'zira"] = true
	names["Q'zira"] = true
	names["Jhal'vira"] = true
	names["Fyr'zira"] = true
	names["Z'zira"] = true
	names["Gral'vira"] = true
	names["Xan'zira"] = true
	names["Thul'vira"] = true
	names["K'zira"] = true
	names["Vor'vira"] = true
	names["Plo'zira"] = true
	names["Quor'vira"] = true
	names["Jy'zira"] = true
	names["Flox'vira"] = true
	names["Zor'zira"] = true
	names["Grax'vira"] = true
	names["Xyl'zira"] = true
	names["Thrak'vira"] = true
	names["K'vira"] = true
	names["Vog'zira"] = true
	names["P'vira"] = true
	names["Quib'zira"] = true
	names["Jax'vira"] = true
	names["Fyn'zira"] = true
	names["Zul'vira"] = true
	names["Grik'zira"] = true
	names["Xe'vira"] = true
	names["Thul'zira"] = true
	names["Kraz'vira"] = true
	names["Vos'zira"] = true
	names["Pry'vira"] = true
	names["Q'vira"] = true
	names["Jho'zira"] = true
	names["Fyr'vira"] = true
	names["Z'vira"] = true
	names["Gren'vira"] = true
	names["Xit'zira"] = true
	names["Trok'vira"] = true
	names["K'zira"] = true
	names["Vol'vira"] = true
	names["P'zira"] = true
	names["Qui'vira"] = true
	names["Jov'zira"] = true
	names["F'vira"] = true
	names["Zal'zira"] = true
	names["Gha'vira"] = true
	names["Xor'zira"] = true
	names["Thra'vira"] = true
	names["Koz'zira"] = true
	names["V'zira"] = true
	names["Phen'zira"] = true
	names["Q'zira"] = true
	names["Jhal'vira"] = true
	names["Fyr'zira"] = true
	nameByIndex := make(map[int]string)
	for k := range names {
		nameByIndex[len(nameByIndex)] = k
	}
	l := len(nameByIndex)
	return nameByIndex[dice.NewDicepool().Sum(fmt.Sprintf("1d%v", l))-1]
}

func RandomLastName() string {
	names := make(map[string]bool)
	names["Valerium"] = true
	names["Navarr"] = true
	names["Corvus"] = true
	names["Orionis"] = true
	names["Solarix"] = true
	names["Cade"] = true
	names["Starkos"] = true
	names["Vega"] = true
	names["Caelum"] = true
	names["Zenith"] = true
	names["Novak"] = true
	names["Cross"] = true
	names["Rook"] = true
	names["Stellan"] = true
	names["Blackwood"] = true
	names["Kael"] = true
	names["Riven"] = true
	names["Crest"] = true
	names["Arden"] = true
	names["Draken"] = true
	names["Rhys"] = true
	names["Jet"] = true
	names["Wilde"] = true
	names["Reed"] = true
	names["Storm"] = true
	names["Hawke"] = true
	names["Vance"] = true
	names["Sable"] = true
	names["Slade"] = true
	names["Blaze"] = true
	names["Knight"] = true
	names["Frost"] = true
	names["Shade"] = true
	names["Stone"] = true
	names["Thorne"] = true
	names["Ash"] = true
	names["Ember"] = true
	names["Phoenix"] = true
	names["Raven"] = true
	names["Shadow"] = true
	names["Cinder"] = true
	names["Gale"] = true
	names["Cliff"] = true
	names["Ridge"] = true
	names["Peak"] = true
	names["Vale"] = true
	names["Brook"] = true
	names["Locke"] = true
	names["Ford"] = true
	names["Ridge"] = true
	names["Wood"] = true
	names["Field"] = true
	names["Glen"] = true
	names["Marsh"] = true
	names["Heath"] = true
	names["Moss"] = true
	names["Pond"] = true
	names["Stream"] = true
	names["Swamp"] = true
	names["Tarn"] = true
	names["Fen"] = true
	names["Bog"] = true
	names["Fjord"] = true
	names["Lake"] = true
	names["Mere"] = true
	names["Pool"] = true
	names["Isle"] = true
	names["Shore"] = true
	names["Bay"] = true
	names["Cape"] = true
	names["Point"] = true
	names["Spit"] = true
	names["Key"] = true
	names["Dune"] = true
	names["Oasis"] = true
	names["Atoll"] = true
	names["Reef"] = true
	names["Cay"] = true
	names["Islet"] = true
	names["Shoal"] = true
	names["Skerry"] = true
	names["Bar"] = true
	names["Spur"] = true
	names["Pass"] = true
	names["Gap"] = true
	names["Col"] = true
	names["Notch"] = true
	names["Defile"] = true
	names["Gorge"] = true
	names["Gully"] = true
	names["Ravine"] = true
	names["Chasm"] = true
	names["Crevasse"] = true
	names["Abyss"] = true
	names["Deep"] = true
	names["Rift"] = true
	names["Summit"] = true
	names["Ridge"] = true
	names["Pinnacle"] = true
	names["Crest"] = true
	names["Spire"] = true
	names["Apex"] = true
	names["Crown"] = true
	names["Cap"] = true
	names["Head"] = true
	names["Tor"] = true
	names["Ben"] = true
	names["Dun"] = true
	names["Mount"] = true
	names["Peak"] = true
	names["Top"] = true
	names["Brow"] = true
	names["Nose"] = true
	names["Shoulder"] = true
	names["Knoll"] = true
	names["Hill"] = true
	names["Down"] = true
	names["Fell"] = true
	names["Law"] = true
	names["Edge"] = true
	names["Bank"] = true
	names["Slope"] = true
	names["Decline"] = true
	names["Incline"] = true
	names["Grade"] = true
	names["Ramp"] = true
	names["Tilt"] = true
	names["List"] = true
	names["Cant"] = true
	names["Lean"] = true
	names["Pitch"] = true
	names["Angle"] = true
	names["Bevel"] = true
	names["Slant"] = true
	names["Camber"] = true
	names["Curve"] = true
	names["Bend"] = true
	names["Arc"] = true
	names["Arch"] = true
	names["Bow"] = true
	names["Coil"] = true
	names["Twist"] = true
	names["Loop"] = true
	names["Spiral"] = true
	names["Helix"] = true
	names["Whorl"] = true
	names["Curlicue"] = true
	names["Volute"] = true
	names["Scroll"] = true
	names["Wave"] = true
	names["Surge"] = true
	names["Swirl"] = true
	names["Eddy"] = true
	names["Drift"] = true
	names["Flow"] = true
	names["Flux"] = true
	names["Tide"] = true
	names["Current"] = true
	names["Stream"] = true
	names["Runnel"] = true
	names["Rill"] = true
	names["Rivulet"] = true
	names["Runnel"] = true
	names["Rill"] = true
	names["Race"] = true
	names["Spate"] = true
	names["Spurt"] = true
	names["Gush"] = true
	names["Spout"] = true
	names["Geyser"] = true
	names["Well"] = true
	names["Fount"] = true
	names["Spring"] = true
	names["Source"] = true
	names["Origin"] = true
	names["Genesis"] = true
	names["Vesper"] = true
	names["Orion"] = true
	names["Cyrus"] = true
	names["Zenon"] = true
	names["Helios"] = true
	names["Atlas"] = true
	names["Perseus"] = true
	names["Arturus"] = true
	names["Draco"] = true
	names["Cassiopeia"] = true
	names["Lyra"] = true
	names["Orionis"] = true
	names["Solarix"] = true
	names["Zenith"] = true
	names["Novak"] = true
	names["Cross"] = true
	names["Rook"] = true
	names["Stellan"] = true
	names["Blackwood"] = true
	names["Kael"] = true
	names["Riven"] = true
	names["Crest"] = true
	names["Arden"] = true
	names["Draken"] = true
	names["Rhys"] = true
	names["Jet"] = true
	names["Wilde"] = true
	names["Reed"] = true
	names["Storm"] = true
	names["Hawke"] = true
	names["Vance"] = true
	names["Sable"] = true
	names["Slade"] = true
	names["Blaze"] = true
	names["Knight"] = true
	names["Frost"] = true
	names["Shade"] = true
	names["Stone"] = true
	names["Thorne"] = true
	names["Ash"] = true
	names["Ember"] = true
	names["Phoenix"] = true
	names["Raven"] = true
	names["Shadow"] = true
	names["Cinder"] = true
	names["Gale"] = true
	names["Cliff"] = true
	names["Ridge"] = true
	names["Peak"] = true
	names["Vale"] = true
	names["Locke"] = true
	names["Ford"] = true
	names["Ridge"] = true
	names["Wood"] = true
	names["Field"] = true
	names["Glen"] = true
	names["Marsh"] = true
	names["Heath"] = true
	names["Moss"] = true
	names["Pond"] = true
	names["Stream"] = true
	names["Swamp"] = true
	names["Tarn"] = true
	names["Fen"] = true
	names["Bog"] = true
	names["Fjord"] = true
	names["Lake"] = true
	names["Mere"] = true
	names["Pool"] = true
	names["Isle"] = true
	names["Shore"] = true
	names["Bay"] = true
	names["Cape"] = true
	names["Point"] = true
	names["Spit"] = true
	names["Key"] = true
	names["Dune"] = true
	names["Oasis"] = true
	names["Atoll"] = true
	names["Reef"] = true
	names["Cay"] = true
	names["Islet"] = true
	names["Shoal"] = true
	names["Skerry"] = true
	names["Bar"] = true
	names["Spur"] = true
	names["Pass"] = true
	names["Gap"] = true
	names["Col"] = true
	names["Notch"] = true
	names["Defile"] = true
	names["Gorge"] = true
	names["Gully"] = true
	names["Ravine"] = true
	names["Chasm"] = true
	names["Crevasse"] = true
	names["Abyss"] = true
	names["Deep"] = true
	names["Rift"] = true
	names["Summit"] = true
	names["Ridge"] = true
	names["Pinnacle"] = true
	names["Crest"] = true
	names["Spire"] = true
	names["Apex"] = true
	names["Crown"] = true
	names["Cap"] = true
	names["Head"] = true
	names["Tor"] = true
	names["Ben"] = true
	names["Dun"] = true
	names["Mount"] = true
	names["Peak"] = true
	names["Top"] = true
	names["Brow"] = true
	names["Nose"] = true
	names["Shoulder"] = true
	names["Knoll"] = true
	names["Hill"] = true
	names["Down"] = true
	names["Fell"] = true
	names["Law"] = true
	names["Edge"] = true
	names["Bank"] = true
	names["Slope"] = true
	names["Decline"] = true
	names["Incline"] = true
	names["Grade"] = true
	names["Ramp"] = true
	names["Tilt"] = true
	names["List"] = true
	names["Cant"] = true
	names["Lean"] = true
	names["Pitch"] = true
	names["Angle"] = true
	names["Bevel"] = true
	names["Slant"] = true
	names["Camber"] = true
	names["Curve"] = true
	names["Bend"] = true
	names["Arc"] = true
	names["Arch"] = true
	names["Bow"] = true
	names["Coil"] = true
	names["Twist"] = true
	names["Loop"] = true
	names["Spiral"] = true
	names["Helix"] = true
	names["Whorl"] = true
	names["Curlicue"] = true
	names["Volute"] = true
	names["Scroll"] = true
	names["Wave"] = true
	names["Surge"] = true
	names["Swirl"] = true
	names["Eddy"] = true
	names["Drift"] = true
	names["Flow"] = true
	names["Flux"] = true
	names["Tide"] = true
	names["Current"] = true
	names["Stream"] = true
	names["Runnel"] = true
	names["Rill"] = true
	names["Rivulet"] = true
	names["Surname"] = true
	names["Ktharr"] = true
	names["Vogorn"] = true
	names["Qitari"] = true
	names["Gornn"] = true
	names["Tchakk"] = true
	names["Laggs"] = true
	names["Vort"] = true
	names["Rinn"] = true
	names["Lyss"] = true
	names["Xxorr"] = true
	names["Linthaar"] = true
	names["Unbrak"] = true
	names["Urzhad"] = true
	names["Gnak"] = true
	names["Hoban"] = true
	names["Antross"] = true
	names["Arrgoth"] = true
	names["Gilmar"] = true
	names["Starnel"] = true
	names["Oortek"] = true
	names["Garnzek"] = true
	names["Kkvol"] = true
	names["Varquisthul"] = true
	names["Bandor"] = true
	names["Zaktar"] = true
	names["Sskhal"] = true
	names["Xxorn"] = true
	names["Anzoth"] = true
	names["Ombrey"] = true
	names["Deklon"] = true
	names["Rakshi"] = true
	names["Argul"] = true
	names["Oskarn"] = true
	names["Kkmor"] = true
	names["Ornsk"] = true
	names["Ixpria"] = true
	names["Lonzar"] = true
	names["Osqen"] = true
	names["Osvell"] = true
	names["Intvor"] = true
	names["Anthzor"] = true
	names["Nalsen"] = true
	names["Ticvell"] = true
	names["Xxarn"] = true
	names["Zarnik"] = true
	names["Osskarr"] = true
	names["Ordis"] = true
	names["Arthvol"] = true
	names["Enkar"] = true
	names["Gontek"] = true
	names["Okarr"] = true
	names["Extern"] = true
	names["Orqex"] = true
	names["Kormax"] = true
	names["Annbor"] = true
	names["Exzul"] = true
	names["Narthel"] = true
	names["Isqarn"] = true
	names["Osskell"] = true
	names["Narzin"] = true
	names["Qethvol"] = true
	names["Illvor"] = true
	names["Othzann"] = true
	names["Onngarr"] = true
	names["Ellzarr"] = true
	names["Nnkort"] = true
	names["Arrzikk"] = true
	names["Lorqex"] = true
	names["Onnvell"] = true
	names["Arzokk"] = true
	names["Qarzann"] = true
	names["Lorthex"] = true
	names["Ossqarn"] = true
	names["Arrzoth"] = true
	names["Ikkvor"] = true
	names["Karnell"] = true
	names["Extall"] = true
	names["Arrzul"] = true
	names["Raknell"] = true
	names["Annkoss"] = true
	names["Orrqex"] = true
	names["Ekvor"] = true
	names["Arrzikk"] = true
	names["Onngess"] = true
	names["Orrtall"] = true
	names["Exzarr"] = true
	names["Orrkess"] = true
	names["Osszann"] = true
	names["Arrnell"] = true
	names["Arrzex"] = true
	names["Orzenn"] = true
	names["Ossbor"] = true
	names["Allzarr"] = true
	names["Exvorn"] = true
	names["Arrnell"] = true
	names["Arrzull"] = true
	names["Orzakk"] = true
	names["Annvoss"] = true
	names["Arrthenn"] = true
	names["Ossqor"] = true
	names["Arrzinn"] = true
	names["Extorr"] = true
	names["Ossborr"] = true
	names["Orzenn"] = true
	names["Arrvokk"] = true
	names["Allzorr"] = true
	names["Exvarr"] = true
	names["Osszenn"] = true
	names["Arrlorr"] = true
	names["Orvinn"] = true
	names["Allqenn"] = true
	names["Exlorr"] = true
	names["Osstenn"] = true
	names["Arrqorr"] = true
	names["Arrtenn"] = true
	names["Orzinn"] = true
	names["Allvarr"] = true
	names["Ossqinn"] = true
	names["Arrborr"] = true
	names["Ortenn"] = true
	names["Ossqarr"] = true
	names["Arrlenn"] = true
	names["Orvarr"] = true
	names["Osslenn"] = true
	names["Arrqarr"] = true
	names["Ortarr"] = true
	names["Osslarr"] = true
	names["Orrtenn"] = true
	names["Ossqorr"] = true
	names["Orrlarr"] = true
	names["Orrqarr"] = true
	names["Osstorr"] = true
	names["Orrlarr"] = true
	names["Ossqorr"] = true
	names["Orrtarr"] = true
	names["Orrqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Orrtarr"] = true
	names["Orrqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Osstarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Ossqarr"] = true
	names["Orrlarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	names["Ossqarr"] = true
	names["Osstarr"] = true
	names["Orrlarr"] = true
	nameByIndex := make(map[int]string)
	for k := range names {
		nameByIndex[len(nameByIndex)] = k
	}
	l := len(nameByIndex)
	return nameByIndex[dice.NewDicepool().Sum(fmt.Sprintf("1d%v", l))-1]
}
