package config

// Config is a travellermap configuration
type Config struct {
	App    AppData `toml:"travellermap"`
	Logger Logger  `toml:"logger"`
	Files  Files   `toml:"files"`
	Maps   Maps    `toml:"maps"`
}

type AppData struct {
	Version string `toml:"version"`
}

type Logger struct {
	Enabled       bool   `toml:"enabled"`
	Filepath      string `toml:"path"`
	Level         string `toml:"logging_level"`
	ConsoleOutput bool   `toml:"console_logging"`
	Color         bool   `toml:"color_output"`
}

type Files struct {
	DataDirectory string `toml:"canonical_data_directory"`
	WorkSpaces    string `toml:"workspaces"`
}

type Maps struct {
	ActiveMap           string          `toml:"active_map"`
	AutoGenerateDetails map[string]bool `toml:"auto_generate_missing_details"`
}

func AutoGenerationMap() map[string]bool {
	agm := make(map[string]bool)
	for _, key := range detailsList() {
		agm[key] = false
	}
	return agm
}

func detailsList() []string {
	return []string{
		"Startport",
	}
}
